import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {photoTransform,transformPhotoUV,createBuildingAssets} from '../src/building-materials.js';
import {prepareBuildingAppearance} from '../src/building-appearance.js';
import {buildBuildingMesh,installBuildingRealism,REALISM_LIMITS,REALISM_PICK_LAYER} from '../src/building-realism.js';
const manifest=JSON.parse(fs.readFileSync(new URL('../dist/data/building-materials.json',import.meta.url))),raw=JSON.parse(fs.readFileSync(new URL('../dist/data/buildings.geojson',import.meta.url))),buildings=prepareBuildingAppearance(raw);
test('projective photo coordinates land on all four source corners without mirroring',()=>{for(const l of manifest.landmarks.filter(l=>l.photo)){const m=photoTransform(l.facadeCorners);assert.ok(m);[[0,0],[1,0],[1,1],[0,1]].forEach(([u,v],i)=>{const [x,y,w]=transformPhotoUV(m,u,v);assert.ok(w>0);assert.ok(Math.abs(x/w-l.facadeCorners[i][0])<1e-6);assert.ok(Math.abs(y/w-l.facadeCorners[i][1])<1e-6);});}assert.equal(photoTransform([[0,0],[1,0],[.5,0],[.2,0]]),null);assert.equal(photoTransform([[0,0],[2,0],[1,1],[0,1]]),null);});
test('release photo assignments have local assets and original author/license records',()=>{assert.equal(manifest.landmarks.filter(l=>l.photo).length,manifest.profile==='procedural'?0:6);if(manifest.profile==='procedural')assert.equal(manifest.materials.length,0);assert.equal(new Set(manifest.materials.map(m=>m.id)).size,manifest.materials.length);for(const m of manifest.materials){assert.ok(m.author);assert.match(m.license,/CC/);assert.match(m.sourcePage,/^https:\/\//);assert.match(m.licenseUrl,/^https:\/\//);for(const p of Object.values(m.maps)){assert.match(p,/^assets\/building-realism\/[\w.-]+$/);assert.ok(fs.statSync(new URL('../dist/'+p,import.meta.url)).size>100);}}for(const l of manifest.landmarks)assert.ok(raw.features.some(f=>f.properties.osm_id===l.osmId));});
test('complete district fits the overview budget with finite normals and source-only photo assignments',()=>{const mesh=buildBuildingMesh(buildings.features,{manifest,detail:false});assert.equal(mesh.included.length,raw.features.length);assert.ok(mesh.vertices.length/mesh.stride<=REALISM_LIMITS.vertices);assert.ok(mesh.vertices.every(Number.isFinite));for(let i=0;i<mesh.vertices.length;i+=mesh.stride){assert.ok(Math.hypot(...mesh.vertices.slice(i+3,i+6))>.99);const kind=mesh.vertices[i+12],layer=mesh.vertices[i+13];assert.ok(layer>=0&&layer<=manifest.materials.length);if(kind===6)assert.equal(manifest.materials[layer-1].type,'photo');}});
test('landmark photos survive reversed polygon winding and remain on the intended face',()=>{for(const l of manifest.landmarks.filter(l=>l.photo)){const f=buildings.features.find(f=>f.properties.osm_id===l.osmId);const original=buildBuildingMesh([f],{manifest,shadows:false}),reversed=structuredClone(f);reversed.geometry.coordinates=reversed.geometry.coordinates.map(r=>r.slice().reverse());const mesh=buildBuildingMesh([reversed],{manifest,shadows:false});const photos=m=>Array.from(m.vertices).filter((_,i)=>i%m.stride===12&&m.vertices[i]===6).length;assert.ok(photos(mesh)>0,l.name);assert.equal(photos(mesh),photos(original));for(let i=0;i<mesh.vertices.length;i+=mesh.stride){if(mesh.vertices[i+12]!==6)continue;const bearing=l.frontBearing*Math.PI/180,dot=mesh.vertices[i+3]*Math.sin(bearing)+mesh.vertices[i+4]*Math.cos(bearing);assert.ok(dot>.75,l.name);}}});
test('too-small geometry budget keeps the entire original building eligible for fallback',()=>{const f=buildings.features.find(f=>f.properties.osm_id==='way/236944775');const mesh=buildBuildingMesh([f],{manifest,detail:true,vertexLimit:30});assert.equal(mesh.included.length,0);assert.equal(mesh.vertices.length,0);});
test('material controller performs no requests until explicitly loaded',()=>{let called=0;const old=globalThis.fetch;globalThis.fetch=()=>{called++;throw Error('unexpected request');};try{const assets=createBuildingAssets('https://example.org/UrbanLens/');assert.equal(called,0);assets.destroy();assert.equal(called,0);}finally{globalThis.fetch=old;}});
test('enhanced geometry preserves picking and restores the original base filter on exit',()=>{const state={realism:true,mode:'3d',theme:'day',schematic:true,terrain:false,layers:{}},original=['==',['get','category'],'building'],styles=new Map([['building-3d',{id:'building-3d',type:'fill-extrusion',source:'buildings',filter:original,paint:{'fill-extrusion-height':['get','render_height']}}]]),events=new Map();const map={getLayer:id=>styles.get(id),getFilter:id=>styles.get(id)?.filter,setFilter:(id,f)=>styles.get(id).filter=f,getStyle:()=>({layers:[...styles.values()]}),setPaintProperty:(id,p,v)=>styles.get(id).paint[p]=v,getPitch:()=>55,getZoom:()=>16,getBounds:()=>({getWest:()=>118.7,getEast:()=>118.9,getSouth:()=>32,getNorth:()=>32.1}),getCenter:()=>({lng:118.81,lat:32.05}),addLayer:l=>styles.set(l.id,l),removeLayer:id=>styles.delete(id),triggerRepaint(){},on:(e,f)=>events.set(e,f),off:e=>events.delete(e)};
 const ui=installBuildingRealism({map,buildings:{features:buildings.features.slice(0,2)},getState:()=>state});assert.equal(styles.get(REALISM_PICK_LAYER).source,'buildings');assert.equal(styles.get(REALISM_PICK_LAYER).paint['fill-extrusion-opacity'],0);assert.notDeepEqual(map.getFilter('building-3d'),original);state.realism=false;ui.sync();assert.deepEqual(map.getFilter('building-3d'),original);assert.equal(styles.has(REALISM_PICK_LAYER),false);ui.destroy();assert.equal(events.size,0);});

test('near-view decoration never displaces complete district buildings',()=>{const mesh=buildBuildingMesh(buildings.features,{manifest,detail:true});assert.equal(mesh.included.length,raw.features.length);assert.ok(mesh.decorationVertices>0);assert.ok(mesh.vertices.length/mesh.stride<=REALISM_LIMITS.vertices);});
test('ordinary facades encode distinct deterministic window families and all roof planes remain finite',()=>{const styles=new Set();for(const f of buildings.features.slice(0,450)){const mesh=buildBuildingMesh([f],{manifest,shadows:false});assert.ok(mesh.vertices.every(Number.isFinite));for(let i=0;i<mesh.vertices.length;i+=mesh.stride){const code=mesh.vertices[i+12],style=Math.floor(code/16)%16;if(style)styles.add(style);}}assert.ok(styles.size>=6);});
