import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {analyzeUnit,businessInput,computeAssessment,createRun,PROFILES} from '../src/value-domain.js';
import {evidenceBasis} from '../src/assessment-evidence.js';
import {validInput} from '../src/assessment-completion.js';
const root=new URL('..',import.meta.url).pathname;
const load=f=>JSON.parse(readFileSync(`${root}/dist/data/${f}.geojson`,'utf8'));
const units=load('research-units').features, data={buildings:load('buildings'),land:load('land')}, services=load('services');
const analyses=new Map(units.map(u=>[u.id,analyzeUnit(u,data,services)]));
const base=units[0], analysis=analyses.get(base.id), geometry=JSON.stringify(base.geometry);
function checkComplete(r){assert.equal(r.coverage,100);assert.equal(r.scores.length,5);assert(r.scores.every(Number.isFinite));assert(Number.isFinite(r.total));assert.equal(r.missing.length,0);assert.equal(r.fieldEvidence.length,6);for(const f of r.fieldEvidence){assert(validInput(f.key,f.value),f.key);assert.equal(f.validity,'valid',f.key);if(f.kind==='simulated')assert.equal(f.verification,'unverified');}}
function recordFor(mode,key,metadata,uploaded={}){const input=businessInput(base,analysis,mode,uploaded);return {[base.id]:{geometry,recordVersion:2,fields:{[key]:{basis:evidenceBasis(input,analysis,{mode,geometry},key),source:'现场核对附件',date:'2026-09-12',validity:'conflict',verification:'unverified',reason:'两份调查来源冲突',refs:[{documentId:'D1',page:2,text:'原始记录'}],...metadata}}}};}
test('hybrid computes all six fields and five scores for eight existing areas and three weight profiles',()=>{for(const u of units)for(const profile of Object.keys(PROFILES))checkComplete(computeAssessment(u,analyses.get(u.id),{mode:'hybrid',profile}));});
test('hybrid supports custom IDs including no numeric suffix, zero, and large suffixes',()=>{for(const id of ['CUSTOM-0','自定义更新片区','CUSTOM-23884898989898989898989']){const unit={...base,id};checkComplete(computeAssessment(unit,analysis,{mode:'hybrid'}));}});
test('simulation is stable across evaluations and object renaming; saved history is immutable',()=>{const run=createRun(base,analysis,{mode:'hybrid'}),saved=JSON.stringify(run),again=computeAssessment(base,analysis,{mode:'hybrid'}),renamed=computeAssessment({...base,id:'CUSTOM-0',properties:{...base.properties,name:'renamed'}},analysis,{mode:'hybrid'});assert.deepEqual(run.input,again.input);assert.deepEqual(run.scores,renamed.scores);assert.equal(run.fingerprint,again.fingerprint);computeAssessment(base,analysis,{mode:'observed'});assert.equal(JSON.stringify(run),saved);});
test('valid uploaded facts including zeros are preferred and preserved with their dates and sources',()=>{const row={buildingArea:0,vacancy:0,industry:'符合',condition:1,source:'现场调查A',date:'2026-09-10'},uploaded={[base.id]:row},before=JSON.stringify(uploaded);const r=computeAssessment(base,analysis,{mode:'hybrid',uploaded});checkComplete(r);for(const key of ['buildingArea','vacancy','industry','condition']){assert.equal(r.input[key],row[key]);const f=r.fieldEvidence.find(f=>f.key===key);assert.equal(f.kind,'uploaded');assert.equal(f.source,row.source);assert.equal(f.date,row.date);}assert.equal(JSON.stringify(uploaded),before);assert.equal(r.simulation.count,0);});
test('missing transit and buildings still produce a complete simulation',()=>{const a={...analysis,nearest:{...analysis.nearest,transit:null},buildingAreaEstimate:0};const r=computeAssessment(base,a,{mode:'hybrid'});checkComplete(r);assert.equal(r.fieldEvidence.find(f=>f.key==='distance').kind,'simulated');assert.equal(r.fieldEvidence.find(f=>f.key==='buildingArea').kind,'simulated');});
test('conflicting hybrid evidence is replaced by a simulation while retaining original evidence',()=>{const uploaded={[base.id]:{buildingArea:10000,vacancy:0,industry:'符合',condition:1,source:'调查',date:'2026-09-10'}},evidenceRecords=recordFor('hybrid','vacancy',{},uploaded),before=JSON.stringify(evidenceRecords);const r=computeAssessment(base,analysis,{mode:'hybrid',uploaded,evidenceRecords});checkComplete(r);const f=r.fieldEvidence.find(f=>f.key==='vacancy');assert.equal(f.kind,'simulated');assert.equal(f.originalEvidence.value,0);assert.equal(f.originalEvidence.validity,'conflict');assert.equal(f.originalEvidence.source,'现场核对附件');assert.equal(f.originalEvidence.refs[0].documentId,'D1');assert.equal(f.verification,'unverified');assert.equal(JSON.stringify(evidenceRecords),before);});
test('a manual verified status never changes a simulated field into verified evidence',()=>{const evidenceRecords=recordFor('hybrid','vacancy',{validity:'valid',verification:'verified'});const r=computeAssessment(base,analysis,{mode:'hybrid',evidenceRecords});assert.equal(r.fieldEvidence.find(f=>f.key==='vacancy').kind,'simulated');assert.equal(r.fieldEvidence.find(f=>f.key==='vacancy').verification,'unverified');});
test('old observed mode retains missing-data behavior; old uploaded complete formula remains unchanged',()=>{const observed=computeAssessment(base,analysis,{mode:'observed'});assert.equal(observed.coverage,20);assert.equal(observed.total,null);const u={id:'CASE',properties:{name:'manual'}},a={area:1000,nearest:{transit:{distance:300}},counts:{},geometryDate:'2026-09-01',spatialDate:'2026-09-02'},uploaded={CASE:{buildingArea:1000,vacancy:25,industry:'待调整',condition:2,source:'QA',date:'2026-09-03'}};const r=computeAssessment(u,a,{mode:'uploaded',uploaded});assert.deepEqual(r.scores,[20,50,80,33.3,25]);assert.equal(r.total,41.7);assert.equal(r.coverage,100);});
test('complete demo mode works for a custom zero-suffixed ID',()=>{checkComplete(computeAssessment({...base,id:'CUSTOM-0'},analysis,{mode:'demo'}));});
test('hybrid must retain a conflict attached to the same uploaded fact from uploaded mode',()=>{const uploaded={[base.id]:{buildingArea:10000,vacancy:0,industry:'符合',condition:1,source:'调查',date:'2026-09-10'}},evidenceRecords=recordFor('uploaded','vacancy',{},uploaded);const original=computeAssessment(base,analysis,{mode:'uploaded',uploaded,evidenceRecords});assert.equal(original.fieldEvidence.find(f=>f.key==='vacancy').validity,'conflict');const r=computeAssessment(base,analysis,{mode:'hybrid',uploaded,evidenceRecords});checkComplete(r);const f=r.fieldEvidence.find(f=>f.key==='vacancy');assert.equal(f.kind,'simulated');assert.equal(f.originalEvidence.validity,'conflict');assert.equal(f.originalEvidence.refs[0].documentId,'D1');});

test('valid geometric area with conflicting evidence is explicit simulation and retains the conflict',()=>{const r=computeAssessment(base,analysis,{mode:'hybrid',evidenceRecords:recordFor('hybrid','area',{})});checkComplete(r);const f=r.fieldEvidence.find(f=>f.key==='area');assert.equal(f.kind,'simulated');assert.equal(f.value,analysis.area);assert.equal(f.originalEvidence.validity,'conflict');assert.equal(f.originalEvidence.refs[0].documentId,'D1');});
