import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdtempSync,writeFileSync,existsSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {projectAPI} from '../server/projects.js';
import {difference,historyComparable} from '../src/comparison-workspace.js';
import {encodeCSV,FIELDS,previewImport} from '../src/project-import.js';
const root=resolve(import.meta.dirname,'..');
class D1{
 constructor(db){this.db=db;}
 prepare(sql){const self=this;return {sql,values:[],bind(...v){this.values=v;return this;},async first(){return self.db.prepare(sql).get(...this.values)||null;},async all(){return {results:self.db.prepare(sql).all(...this.values)};},async run(){const r=self.db.prepare(sql).run(...this.values);return {success:true,meta:{changes:Number(r.changes)}};}};}
 async batch(qs){this.db.exec('BEGIN');try{const out=[];for(const q of qs)out.push(await q.run());this.db.exec('COMMIT');return out;}catch(e){this.db.exec('ROLLBACK');throw e;}}
}
function diskBucket(dir){return {async put(key,value){const p=join(dir,key);mkdirSync(resolve(p,'..'),{recursive:true});writeFileSync(p,typeof value==='string'?value:Buffer.from(value));},async get(key){const p=join(dir,key);if(!existsSync(p))return null;const bytes=readFileSync(p);return {body:bytes,json:async()=>JSON.parse(bytes.toString())};}};}
test('durable projects, permissions, imports, immutable results and concurrency',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'urbanlens-project-')),db=new DatabaseSync(join(dir,'db.sqlite'));db.exec(readFileSync(join(root,'drizzle/0000_young_doorman.sql'),'utf8'));const env={DB:new D1(db),BUCKET:diskBucket(dir),ASSETS:{async fetch(req){try{return new Response(readFileSync(join(root,'dist',new URL(req.url).pathname)),{headers:{'Content-Type':'application/json'}});}catch{return new Response('',{status:404});}}}};
 const call=async(user,path='',value,extra={})=>{const response=await projectAPI(new Request('https://urban.test/api/'+path,{method:value?'POST':'GET',headers:{...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{}),...(value?{'Content-Type':'application/json',Origin:'https://urban.test'}:{}),...extra},body:value?JSON.stringify(value):undefined}),env);return {status:response.status,value:await response.json()};};
 const get=async(pid,user='owner')=>(await call(user,'projects/'+pid)).value;
 const create=async(name='测试项目')=>{const r=await call('owner','projects',{name,description:'集成验收数据',template:'xuanwu'});assert.equal(r.status,201,JSON.stringify(r));return r.value.id;};
 let pid,other,runs,firstVersion;
 try{
 await t.test('identity required and projects private by default',async()=>{assert.equal((await call(null,'projects')).status,401);pid=await create();other=await create('独立项目');await call('viewer','me');await call('editor','me');assert.equal((await call('viewer','projects')).value.projects.length,0);assert.equal((await call('viewer','projects/'+pid)).status,404);});
 await t.test('role grants, read-only and member management server enforcement',async()=>{for(const [userId,role]of [['viewer','viewer'],['editor','editor']]){const p=(await get(pid)).project;assert.equal((await call('owner',`projects/${pid}/members`,{revision:p.revision,userId,role})).status,200);}assert.equal((await call('viewer','projects/'+pid)).status,200);for(const route of ['state','evaluate','imports/preflight','imports/commit','reports','attachments','restore','data/clear','metadata','comparisons','evidence','reviews'])assert.equal((await call('viewer',`projects/${pid}/${route}`,{})).status,403,route);assert.equal((await call('viewer',`projects/${pid}/archive`,{})).status,403);assert.equal((await call('editor',`projects/${pid}/members`,{})).status,403);assert.equal((await call('editor',`projects/${pid}/archive`,{})).status,403);});
 await t.test('preflight blocks invalid mappings, unmatched and duplicate IDs',async()=>{const p=await get(pid);const fields=FIELDS.map(([k])=>k),rows=[['XW-R01','30000','25','符合','2','验收台账','2026-09-12'],['XW-R01','30000','25','符合','2','重复','2026-09-12'],['FOREIGN','','25','符合','2','未知','2026-09-12']];const r=await call('editor',`projects/${pid}/imports/preflight`,{revision:p.project.revision,kind:'csv',text:encodeCSV([fields,...rows])});assert.equal(r.status,200);assert.equal(r.value.canCommit,false);assert.equal(r.value.errors.length,2);const commit=await call('editor',`projects/${pid}/imports/commit`,{revision:p.project.revision,token:r.value.token,decisions:{}});assert.equal(commit.status,422);assert.deepEqual((await get(pid)).data,p.data);});
 await t.test('server computes saved runs tied to project data versions',async()=>{const p=await get(pid);firstVersion=structuredClone(p.data);const r=await call('editor',`projects/${pid}/evaluate`,{revision:p.project.revision,unitIds:['XW-R01','XW-R03'],mode:'demo',profile:'balanced'});assert.equal(r.status,200,JSON.stringify(r));runs=r.value.runs;assert.equal(runs.length,2);assert.equal(runs[0].projectId,pid);assert.equal(runs[0].projectDataVersion,1);assert.ok(runs[0].geometry);});
 await t.test('import with mapped fields and units creates new data version, idempotent retry',async()=>{const p=await get(pid);const r=await call('editor',`projects/${pid}/imports/preflight`,{revision:p.project.revision,kind:'csv',text:encodeCSV([['编号','建筑面积','空置率','产业','等级','来源','日期'],['XW-R01','3','0.25','符合','2','现场调查','2026-09-12']]),mapping:{parcel_id:'编号',building_area_m2:'建筑面积',vacancy_pct:'空置率',industry:'产业',condition:'等级',source:'来源',date:'日期'},areaUnit:'ha',vacancyUnit:'fraction'});assert.equal(r.value.canCommit,true,JSON.stringify(r));const b={revision:p.project.revision,token:r.value.token,decisions:{}};const saved=await call('editor',`projects/${pid}/imports/commit`,b);assert.equal(saved.status,200);assert.equal(saved.value.dataVersion,2);assert.equal((await call('editor',`projects/${pid}/imports/commit`,b)).value.alreadyCommitted,true);const next=await get(pid);assert.equal(next.data.uploaded['XW-R01'].buildingArea,30000);assert.equal(next.data.uploaded['XW-R01'].vacancy,25);assert.deepEqual(next.runs,runs);});
 await t.test('conflicting source requires explicit choice and preserves both sources',async()=>{const p=await get(pid);const r=await call('editor',`projects/${pid}/imports/preflight`,{revision:p.project.revision,kind:'csv',name:'conflict.csv',text:encodeCSV([FIELDS.map(([k])=>k),['XW-R01','40000','30','待调整','3','另一来源','2026-09-12']])});assert.equal(r.value.conflicts.length,1);assert.equal((await call('editor',`projects/${pid}/imports/commit`,{revision:p.project.revision,token:r.value.token,decisions:{}})).status,422);assert.equal((await call('editor',`projects/${pid}/imports/commit`,{revision:p.project.revision,token:r.value.token,decisions:{'XW-R01':'existing'}})).status,200);const next=await get(pid);assert.equal(next.data.uploaded['XW-R01'].buildingArea,30000);const a=next.artifacts.find(a=>a.name==='conflict.csv');const saved=(await call('viewer',`projects/${pid}/artifacts/${a.id}`)).value.value;assert.equal(saved.preview.conflicts[0].old.buildingArea,30000);assert.equal(saved.preview.conflicts[0].incoming.buildingArea,40000);});
 await t.test('stale editors cannot overwrite, no partial writes',async()=>{const p=await get(pid);const state={mode:'demo',profile:'balanced',selected:'XW-R01',compared:[],history:[],scenario:{far:1.8,retain:70,publicShare:25}};assert.equal((await call('editor',`projects/${pid}/state`,{revision:p.project.revision,state})).status,200);assert.equal((await call('editor',`projects/${pid}/state`,{revision:p.project.revision,state:{...state,profile:'public'}})).status,409);assert.equal((await get(pid)).project.state.profile,'balanced');});
 await t.test('attachments, reports and comparison endpoints enforce parent project',async()=>{const p=await get(pid);const m={run:runs[0],sections:[],subtitle:'测试报告',mapImage:'data:image/png;base64,aA=='};const report=await call('editor',`projects/${pid}/reports`,{revision:p.project.revision,model:m});assert.equal(report.status,200);const rid=report.value.model.id;assert.equal((await call('owner',`projects/${other}/artifacts/${rid}`)).status,404);const p2=await get(pid);assert.equal((await call('editor',`projects/${pid}/reports`,{revision:p2.project.revision,model:{...report.value.model,note:'覆盖旧版本'}})).status,409);const q=(await get(other)).project;assert.equal((await call('owner',`projects/${other}/comparisons`,{revision:q.revision,type:'units',runIds:runs.map(r=>r.id)})).status,404);const a=await call('editor',`projects/${pid}/attachments`,{revision:p2.project.revision,name:'说明.txt',mime:'text/plain',base64:btoa('test attachment')});assert.equal(a.status,200);assert.equal((await call('owner',`projects/${other}/artifacts/${a.value.id}`)).status,404);});
 await t.test('report families use a monotonic revision even when editing an older parent',async()=>{const saved=(await get(pid)).artifacts.find(a=>a.kind==='report'),first=(await call('editor',`projects/${pid}/artifacts/${saved.id}`)).value.value;let p=await get(pid);const model={...first,note:'second'};delete model.id;const second=await call('editor',`projects/${pid}/reports`,{revision:p.project.revision,parentId:first.id,model});assert.equal(second.value.model.revision,2);p=await get(pid);const third=await call('editor',`projects/${pid}/reports`,{revision:p.project.revision,parentId:first.id,model:{...model,note:'third from first'}});assert.equal(third.value.model.revision,3);assert.equal(third.value.model.parentId,first.id);});
 await t.test('saved comparison preserves the chosen baseline and immutable runs',async()=>{const p=await get(pid),r=await call('editor',`projects/${pid}/comparisons`,{revision:p.project.revision,type:'units',runIds:runs.map(r=>r.id),baselineRunId:runs[1].id});assert.equal(r.status,200);assert.equal(r.value.snapshot.baselineRunId,runs[1].id);const stored=(await call('viewer',`projects/${pid}/artifacts/${r.value.snapshot.id}`)).value.value;assert.deepEqual(stored.runs,runs);assert.equal(stored.baselineRunId,runs[1].id);});
 await t.test('invalid state cannot break the project on reload',async()=>{const p=await get(pid),state={mode:'demo',profile:'balanced',selected:'XW-R01',compared:[],history:[],scenario:null};assert.equal((await call('editor',`projects/${pid}/state`,{revision:p.project.revision,state})).status,400);state.scenario={far:1.8,retain:70,publicShare:25};state.history=[{question:'malformed'}];assert.equal((await call('editor',`projects/${pid}/state`,{revision:p.project.revision,state})).status,400);assert.equal((await get(pid)).project.revision,p.project.revision);});
 await t.test('evidence versions, page references, reviews and server-built reports',async()=>{
  const evidencePid=await create('第三步证据验收'),route=`projects/${evidencePid}`;
  let p=await get(evidencePid);
  const txt='规划核对记录\f安全资料：需补充鉴定';
  let doc=await call('owner',route+'/attachments',{revision:p.project.revision,name:'核对依据.txt',mime:'text/plain',base64:Buffer.from(txt).toString('base64')});assert.equal(doc.status,200,JSON.stringify(doc));
  const documents=(await call('owner',route+'/documents')).value.documents;assert.equal(documents[0].pages.length,2);assert.equal(documents[0].pages[1].text,'安全资料：需补充鉴定');assert.match(documents[0].sha256,/^[0-9a-f]{64}$/);
  const reference={documentId:doc.value.documentId,page:2};p=await get(evidencePid);
  let first=await call('owner',route+'/evaluate',{revision:p.project.revision,unitIds:['XW-R01'],mode:'demo',profile:'balanced'});assert.equal(first.status,200);const original=structuredClone(first.value.runs[0]);
  p=await get(evidencePid);const evidence={revision:p.project.revision,unitId:'XW-R01',mode:'demo',fields:{vacancy:{source:'独立核对',date:'2026-09-11',validity:'conflict',verification:'unverified',reason:'调查口径冲突',refs:[reference]}},constraints:{safety:{status:'issue',summary:'需补充安全鉴定',date:'2026-09-11',refs:[reference]}}};
  assert.equal((await call('owner',route+'/evidence',{...evidence,constraints:{safety:{status:'checked',summary:'已核对',date:'2026-09-11',refs:[]}}})).status,422);
  assert.equal((await call('owner',route+'/evidence',{...evidence,fields:{...evidence.fields,vacancy:{...evidence.fields.vacancy,refs:[{...reference,page:99}]}}})).status,422);
  assert.equal((await call('owner',route+'/evidence',evidence)).status,200);p=await get(evidencePid);assert.equal(p.project.data_version,2);assert.deepEqual(p.runs[0],original);
  assert.equal((await call('owner',route+'/reviews',{revision:p.project.revision,runId:original.id,status:'reviewed',note:'旧数据'})).status,409);
  const evaluated=await call('owner',route+'/evaluate',{revision:p.project.revision,unitIds:['XW-R01'],mode:'demo',profile:'balanced'});assert.equal(evaluated.status,200);const run=evaluated.value.runs[0];assert.equal(run.total,null);assert.equal(run.coverage,80);assert.notEqual(run.fingerprint,original.fingerprint);assert.equal(run.fieldEvidence.find(f=>f.key==='vacancy').validity,'conflict');assert.equal(run.constraints.find(c=>c.category==='safety').refs[0].text,'安全资料：需补充鉴定');
  p=await get(evidencePid);const review=await call('owner',route+'/reviews',{revision:p.project.revision,runId:run.id,status:'changes',note:'补充资料后重算',actorId:'forged',actorName:'伪造姓名'});assert.equal(review.status,200);assert.equal(review.value.review.actorId,'owner');assert.notEqual(review.value.review.actorName,'伪造姓名');
  p=await get(evidencePid);const report=await call('owner',route+'/reports',{revision:p.project.revision,model:{run,sections:[{title:'伪造总分',paragraphs:['100 分']}],note:'人工研究叙述',reviewer:'伪造复核',status:'正式通过',reviewId:review.value.review.id,mapImage:'data:image/png;base64,aA=='}});assert.equal(report.status,200,JSON.stringify(report));assert.equal(report.value.model.status,'需补充资料');assert.equal(report.value.model.reviewer,review.value.review.actorName);assert.equal(report.value.model.sections.some(s=>s.title==='伪造总分'),false);assert.equal(report.value.model.sections.some(s=>s.title==='独立约束'),true);
  const rid=report.value.model.id;p=await get(evidencePid);assert.equal((await call('owner',route+'/evidence',{...evidence,revision:p.project.revision,fields:{}})).status,200);const old=(await call('owner',route+'/artifacts/'+rid)).value.value;assert.deepEqual(old,report.value.model);
  assert.equal((await call('owner',`projects/${other}/artifacts/${doc.value.documentId}`)).status,404);
 });
 await t.test('restore creates new version and retains original runs',async()=>{const p=await get(pid);const r=await call('editor',`projects/${pid}/restore`,{revision:p.project.revision,version:1});assert.equal(r.status,200);assert.ok(r.value.dataVersion>1);const next=await get(pid);assert.deepEqual(next.data,firstVersion);assert.deepEqual(next.runs,runs);});
 await t.test('database and blob storage reopen with all project objects present',async()=>{const before=await get(pid);env.DB=new D1(new DatabaseSync(join(dir,'db.sqlite')));env.BUCKET=diskBucket(dir);const after=await get(pid);assert.deepEqual(after.data,before.data);assert.deepEqual(after.runs,before.runs);assert.deepEqual(after.artifacts,before.artifacts);});
 await t.test('drawn areas persist, hybrid scores complete and viewer cannot modify or run',async()=>{
  const cp=await create('自定义片区试算');let p=await get(cp);await call('owner',`projects/${cp}/members`,{revision:p.project.revision,userId:'viewer',role:'viewer'});p=await get(cp);
  const feature={type:'Feature',properties:{parcel_id:'CUSTOM-CHECK',name:'自定义验收范围'},geometry:{type:'Polygon',coordinates:[[[118.79,32.05],[118.795,32.05],[118.795,32.055],[118.79,32.055],[118.79,32.05]]]}};
  const payload={revision:p.project.revision,kind:'geojson',name:'drawn.geojson',text:JSON.stringify({type:'FeatureCollection',features:[feature]})};
  assert.equal((await call('viewer',`projects/${cp}/imports/preflight`,payload)).status,403);
  const pre=await call('owner',`projects/${cp}/imports/preflight`,payload);assert.equal(pre.status,200);assert.equal(pre.value.canCommit,true);
  const committed=await call('owner',`projects/${cp}/imports/commit`,{revision:p.project.revision,token:pre.value.token,decisions:{}});assert.equal(committed.status,200);p=await get(cp,'viewer');assert.deepEqual(p.data.units.at(-1).geometry,feature.geometry);assert.equal(p.project.data_version,2);
  const options={revision:p.project.revision,unitIds:['XW-R01','CUSTOM-CHECK'],mode:'hybrid',profile:'public'};assert.equal((await call('viewer',`projects/${cp}/evaluate`,options)).status,403);
  const evaluated=await call('owner',`projects/${cp}/evaluate`,options);assert.equal(evaluated.status,200);for(const r of evaluated.value.runs){assert.equal(r.coverage,100);assert(Number.isFinite(r.total));assert.equal(r.projectDataVersion,2);assert(r.simulation.count>0);assert(r.fieldEvidence.filter(f=>f.kind==='simulated').every(f=>f.verification==='unverified'));}
  const reread=await get(cp,'viewer');assert.deepEqual(reread.runs,evaluated.value.runs);assert.equal((await call('editor',`projects/${cp}/artifacts/${reread.runs[0].id}`)).status,404);
 });
 await t.test('archive is durable and blocks writes until restored',async()=>{let p=await get(pid);assert.equal((await call('owner',`projects/${pid}/archive`,{revision:p.project.revision,status:'archived'})).status,200);assert.equal((await get(pid,'viewer')).project.status,'archived');assert.equal((await call('editor',`projects/${pid}/evaluate`,{})).status,409);p=await get(pid);assert.equal((await call('owner',`projects/${pid}/archive`,{revision:p.project.revision,status:'active'})).status,200);});
 await t.test('revoked access fails immediately; cross-site writes rejected',async()=>{const p=await get(pid);assert.equal((await call('owner',`projects/${pid}/members`,{revision:p.project.revision,userId:'viewer',role:'remove'})).status,200);assert.equal((await call('viewer','projects/'+pid)).status,404);assert.equal((await call('viewer',`projects/${pid}/artifacts/${runs[0].id}`)).status,404);assert.equal((await call('owner','projects',{name:'CSRF',description:'',template:'empty'},{Origin:'https://attacker.test'})).status,403);});
 }finally{db.close();rmSync(dir,{recursive:true,force:true});}
});
test('comparison deltas preserve missing values and percentage points',()=>{assert.equal(difference(null,10,'%'),'—');assert.equal(difference(0,10,'%'),'+10 个百分点');assert.equal(difference(20,15,'分'),'-5 分');assert.equal(historyComparable([{unitId:'a',mode:'demo',ruleVersion:'r',dimensions:[{weight:1}]},{unitId:'a',mode:'demo',ruleVersion:'s',dimensions:[{weight:1}]}]),false);});
test('geometry precheck rejects self-intersections before commit',()=>{const boundary=JSON.parse(readFileSync(join(root,'dist/data/boundary.geojson'))).features[0].geometry;const p=previewImport({kind:'geojson',text:JSON.stringify({type:'FeatureCollection',features:[{type:'Feature',properties:{parcel_id:'TEST'},geometry:{type:'Polygon',coordinates:[[[118.8,32.06],[118.804,32.064],[118.8,32.063],[118.804,32.06],[118.8,32.06]]]}}]})},{units:[],uploaded:{}},boundary);assert.equal(p.canCommit,false);});
