import {parseHTML} from "linkedom";
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {ValueStudio} from '../src/value-studio.js';
import {ProjectWorkspace} from '../src/project-workspace.js';
import {EvaluationWorkspace} from '../src/evaluation-workspace.js';
import {analyzeUnit} from '../src/value-domain.js';
const root=new URL('..',import.meta.url).pathname;
const load=f=>JSON.parse(readFileSync(`${root}/dist/data/${f}.geojson`,'utf8'));
const units=load('research-units').features,data={buildings:load('buildings'),land:load('land')},services=load('services');
function studio(){const s=Object.create(ValueStudio.prototype);Object.assign(s,{units:structuredClone(units),analyses:new Map(units.map(u=>[u.id,analyzeUnit(u,data,services)])),state:{selected:units[0].id,mode:'hybrid',profile:'balanced',runs:[],compared:[],uploaded:{}},adapter:{toast(){},drawArea(){},cancelDrawing(){}},render(){},radar(){return '<svg data-qa="radar"></svg>';},setView(v){this.state.view=v;}});return s;}
test('only a workspace with no project can run local trials; viewer, archived, disconnected and switching projects cannot',async()=>{const s=studio();s.cloud={current:null,switching:false};assert.equal(s.canCalculate,true);const first=await s.evaluateUnits([units[0].id]);assert.equal(first[0].trial,true);assert.equal(first[0].coverage,100);const saved=JSON.stringify(s.state.runs);for(const scenario of [{role:'viewer',status:'active',connected:true,switching:false},{role:'editor',status:'archived',connected:true,switching:false},{role:'editor',status:'active',connected:false,switching:false},{role:'editor',status:'active',connected:true,switching:true}]){const p=Object.create(ProjectWorkspace.prototype);Object.assign(p,{studio:s,current:{project:{id:'P1',role:scenario.role,status:scenario.status}},transport:{connected:scenario.connected},switching:scenario.switching});s.cloud=p;assert.equal(s.canCalculate,false);await assert.rejects(()=>s.evaluateUnits([units[0].id]),/只读/);assert.equal(JSON.stringify(s.state.runs),saved);}s.cloud={current:null,switching:true};assert.equal(s.canCalculate,false);await assert.rejects(()=>s.evaluateUnits([units[0].id]),/切换/);});
test('drawn draft is discarded when project identity changes before accepting it',async()=>{const s=studio();s.cloud={current:null,pid:undefined,epoch:1,switching:false};s.beginDrawing('polygon');s.cloud.epoch=2;await assert.rejects(()=>s.acceptDrawnArea({}),/项目或权限已变化/);assert.equal(s.state.runs.length,0);});
test('step 3 renders trial state and step 4 routes temporary results to project creation',async()=>{const s=studio();s.cloud={current:null,switching:false};await s.evaluateUnits([units[0].id]);const before=globalThis.document,raf=globalThis.cancelAnimationFrame;globalThis.document=parseHTML('<html><body><div id="value-detail"></div></body></html>').document;globalThis.cancelAnimationFrame=()=>{};const detail=globalThis.document.querySelector('#value-detail');try{const e=Object.create(EvaluationWorkspace.prototype);e.s=s;e.budgets=new Map();e.revealed=new Set();e.step=3;e.render();assert.match(detail.innerHTML,/临时试算/);assert.match(detail.innerHTML,/计算完整性 100%/);assert.match(detail.innerHTML,/保存到项目/);assert.doesNotMatch(detail.innerHTML,/<form id="assessment-review"/);e.step=4;e.render();assert.match(detail.innerHTML,/连接并保存为项目/);assert.doesNotMatch(detail.innerHTML,/data-v-action="report"/);assert.doesNotMatch(detail.innerHTML,/<form id="assessment-review"/);}finally{globalThis.document=before;globalThis.cancelAnimationFrame=raf;}});
test('viewer sees saved results with disabled evaluation and review submission',async()=>{const s=studio();s.cloud={current:null,switching:false};const [run]=await s.evaluateUnits([units[0].id]);delete run.trial;run.projectDataVersion=1;s.cloud={current:{project:{id:'P1',data_version:1},data:{evidence:{}},reviews:[]},canEdit:false};const before=globalThis.document,raf=globalThis.cancelAnimationFrame;globalThis.document=parseHTML('<html><body><div id="value-detail"></div></body></html>').document;globalThis.cancelAnimationFrame=()=>{};const detail=globalThis.document.querySelector('#value-detail');try{const e=Object.create(EvaluationWorkspace.prototype);e.s=s;e.budgets=new Map();e.revealed=new Set();e.step=3;e.render();assert.match(detail.innerHTML,/data-e-action="evaluate" disabled/);assert.match(detail.innerHTML,/已保存结果/);e.step=4;e.render();assert.match(detail.innerHTML,/<button class="outline-button" disabled>以当前账户提交复核/);assert.match(detail.innerHTML,/data-v-action="report"/);}finally{globalThis.document=before;globalThis.cancelAnimationFrame=raf;}});
test('migration validates and commits all temporary boundaries before any evaluation',async()=>{const s=studio(),p=Object.create(ProjectWorkspace.prototype),calls=[];Object.assign(p,{studio:s,current:{project:{id:'P1',revision:1}},epoch:4,async api(path,body){calls.push('preflight');assert.equal(path,'projects/P1/imports/preflight');const features=JSON.parse(body.text).features;assert.equal(features.length,units.length);assert(features.every(f=>f.properties.parcel_id===f.id));return {canCommit:true,token:'T1'};},async mutation(route,body,refresh){calls.push('commit');assert.equal(route,'imports/commit');assert.equal(body.token,'T1');assert.equal(refresh,true);},async evaluate(ids){calls.push('evaluate');assert(ids.length<=3);assert.equal(s.state.mode,'demo');assert.equal(s.state.profile,'public');assert.equal(s.state.selected,units[3].id);assert.deepEqual(s.state.compared,units.slice(0,2).map(u=>u.id));}});s.persist=()=>{};await p.saveTrialAreas({units,mode:'demo',profile:'public',selected:units[3].id,compared:units.slice(0,2).map(u=>u.id),evaluated:units.slice(0,7).map(u=>u.id)});assert.deepEqual(calls,['preflight','commit','evaluate','evaluate','evaluate']);});
test('migration stops if a different project is entered while boundary preflight is pending',async()=>{const s=studio(),p=Object.create(ProjectWorkspace.prototype);Object.assign(p,{studio:s,current:{project:{id:'P1',revision:1}},epoch:4,async api(){this.current={project:{id:'P2',revision:1}};this.epoch=5;return {canCommit:true,token:'T1'};},async mutation(){assert.fail('must not commit into another project');}});await assert.rejects(()=>p.saveTrialAreas({units,evaluated:[]}),/项目已切换/);});
test('new project snapshots the current trial configuration before opening the new cloud project',async()=>{const s=studio();s.state.mode='demo';s.state.profile='public';s.state.selected=units[2].id;s.state.compared=units.slice(0,2).map(u=>u.id);s.state.runs=[{trial:true,unitId:units[2].id,mode:'demo',profile:'public'},{trial:true,unitId:units[0].id,mode:'hybrid',profile:'balanced'}];const p=Object.create(ProjectWorkspace.prototype),form={},beforeDoc=globalThis.document,beforeFormData=globalThis.FormData;let captured;Object.assign(p,{studio:s,current:null,dialog(){},async api(path,body){assert.equal(path,'projects');assert.equal(body.template,'trial');return {id:'NEW'};},async open(id){this.current={project:{id}};s.state={mode:'hybrid',profile:'balanced'};},async saveTrialAreas(trial){captured=trial;},showError(e){throw e;}});globalThis.document={querySelector:()=>form};globalThis.FormData=class{[Symbol.iterator](){return [['name','迁移测试'],['description',''],['template','trial']][Symbol.iterator]();}};try{p.newProject();const button={disabled:false};await form.onsubmit({preventDefault(){},target:form,submitter:button});assert.equal(button.disabled,false);assert.equal(captured.mode,'demo');assert.equal(captured.profile,'public');assert.equal(captured.selected,units[2].id);assert.deepEqual(captured.compared,units.slice(0,2).map(u=>u.id));assert.deepEqual(captured.evaluated,[units[2].id]);assert.equal(captured.units.length,8);}finally{globalThis.document=beforeDoc;globalThis.FormData=beforeFormData;}});
