import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {gunzipSync} from 'node:zlib';
import proj4 from 'proj4';
import {unzipSync,strFromU8} from 'fflate';
import {projectedArea,referencePoint,analyzeUnit,computeAssessment,createRun,compareRuns,capacityScenario,marketMeasures,parseBusinessCSV,answerQuestion,PROFILES} from '../src/value-domain.js';
import {reportModel,reportDocx,reportMarkdown} from '../src/value-report.js';
import {inGeometry,validateImport,boundsOf} from '../src/geo.js';
import {ValueStudio} from '../src/value-studio.js';
import {cameraInScope} from '../src/studio-shell.js';
const load=f=>{const path=new URL('../dist/data/'+f,import.meta.url);if(fs.existsSync(path))return JSON.parse(fs.readFileSync(path));const root=new URL('../dist/packed/',import.meta.url),m=JSON.parse(fs.readFileSync(new URL('services.json',root)));return JSON.parse(gunzipSync(Buffer.concat(m.parts.map(p=>fs.readFileSync(new URL(p,root))))));};
const data=Object.fromEntries(['buildings','land'].map(k=>[k,load(k+'.geojson')])),services=load('services.geojson'),units=load('research-units.geojson').features,evidence=load('value-evidence.json');
const analyses=new Map(units.map(u=>[u.id,analyzeUnit(u,data,services)]));
const calc=(i=0,opts={})=>{const unit=typeof i==='string'?units.find(u=>u.id===i):units[i];return computeAssessment(unit,analyses.get(unit.id),opts);};
test('projected square area includes holes without treating longitude degrees as meters',()=>{const utm=proj4('EPSG:4326','+proj=utm +zone=50 +datum=WGS84 +units=m +no_defs');const rect=(x,y,w,h)=>[[x,y],[x+w,y],[x+w,y+h],[x,y+h],[x,y]].map(p=>utm.inverse(p));const geometry={type:'Polygon',coordinates:[rect(670000,3550000,100,200),rect(670020,3550020,10,20)]};assert(Math.abs(projectedArea(geometry)-19800)<.01);assert(inGeometry(referencePoint(geometry),geometry));});
test('all six districts have real research units with interior reference points, plausible area and dated spatial evidence',()=>{assert(units.length>=24);assert.equal(new Set(units.map(u=>u.properties.division_code)).size,6);for(const u of units){const a=analyses.get(u.id);assert(inGeometry(a.point,u.geometry));assert(a.area>1000&&a.area<2e6);assert(a.nearest.transit.distance>=0);assert.equal(a.spatialDate,services.metadata.snapshotAt);assert.equal(a.geometryDate,u.properties.source_date||data.land.metadata.snapshotAt);assert(Number.isFinite(Date.parse(a.geometryDate)));}});
test('service references preserve attribution, dedup IDs and category totals',()=>{assert.equal(services.metadata.count,services.features.length);assert.equal(Object.values(services.metadata.counts).reduce((s,n)=>s+n,0),services.features.length);assert.equal(new Set(services.features.flatMap(f=>f.properties.related_osm_ids)).size,services.metadata.classifiedCount);assert.equal(services.metadata.license,'ODbL 1.0');});
test('public data cannot fabricate business facts or a full aggregate',()=>{for(let i=0;i<units.length;i++){const r=calc(i);assert.equal(r.input.buildingArea,null);assert.equal(r.input.vacancy,null);assert.equal(r.total,null);assert.equal(r.coverage,20);assert.equal(r.dimensions[0].status,'开放数据计算');}});
test('demo scores reproduce independent weighted sums and mark fabricated business attributes',()=>{for(const profile of Object.keys(PROFILES))for(let i=0;i<units.length;i++){const r=calc(i,{mode:'demo',profile});if((Number(units[i].id.match(/\d+$/)?.[0]||1)-1)%8===6){assert.equal(r.total,null);assert(r.coverage<100);}else{const expected=Math.round(r.scores.reduce((s,n,j)=>s+n*PROFILES[profile].weights[j],0)*10)/10;assert.equal(r.total,expected);assert.equal(r.coverage,100);}assert(r.input.source.includes('虚构'));}});
test('valid zero vacancy is retained and contributes a real zero rather than missingness',()=>{const r=calc('XW-R08',{mode:'demo'});assert.equal(r.input.vacancy,0);assert.equal(r.scores[4],0);assert.equal(r.coverage,100);});
test('run snapshots remain unchanged across data modes and input versions',()=>{const run=createRun(units[0],analyses.get(units[0].id),{mode:'demo'}),saved=JSON.stringify(run),other=calc(0);assert.notEqual(run.fingerprint,other.fingerprint);assert.equal(JSON.stringify(run),saved);assert.equal(run.review.status,'未复核');});
test('comparison blocks mixed modes, rules, dates and incomplete indicators',()=>{const a=calc(0,{mode:'demo'}),b=calc(1,{mode:'demo'});assert.equal(compareRuns([a,b]).ranked.length,2);for(const x of [calc(1),calc(1,{mode:'demo',profile:'public'}),calc('XW-R07',{mode:'demo'}),{...b,input:{...b.input,date:'2025-01-01'}}])assert.equal(compareRuns([a,x]).ranked.length,0);});
test('capacity scenarios are deterministic assumptions and retain missing current area',()=>{const r=capacityScenario(10000,15000,{far:2,retain:80,publicShare:25});assert.equal(r.target,20000);assert.equal(r.retained,12000);assert.equal(r.additional,8000);assert.equal(r.publicArea,2500);assert.equal(capacityScenario(10000,null,{far:2,retain:80,publicShare:25}).additional,null);assert.throws(()=>capacityScenario(10000,2,{far:-1,retain:50,publicShare:25}));assert(capacityScenario(10000,50000,{far:1,retain:100,publicShare:25}).excess);});
test('historical price conversion handles yuan versus ten thousand yuan',()=>{assert.deepEqual(marketMeasures({area_m2:10000,far_max:2,start_wan:10000,deal_wan:12000}),{floorPrice:6000,premium:20});assert.equal(marketMeasures(evidence.market[0]).floorPrice,37875);assert.equal(marketMeasures(evidence.market[1]).premium,0);});
const header='parcel_id,building_area_m2,vacancy_pct,industry,condition,source,date\n';
test('CSV joins are atomic and preserve valid zeros, nulls, quoted sources and provenance',()=>{const ids=units.map(u=>u.id);const text=header+'XW-R01,0,0,符合,1,"调查,附件",2026-09-12\nXW-R02,,,待核实,,来源B,2026-09-11';const r=parseBusinessCSV(text,ids);assert.equal(r['XW-R01'].buildingArea,0);assert.equal(r['XW-R01'].vacancy,0);assert.equal(r['XW-R02'].buildingArea,null);assert.equal(r['XW-R01'].source,'调查,附件');for(const bad of ['XW-R99,1,0,符合,1,a,2026-09-12','XW-R01,1,101,符合,1,a,2026-09-12','XW-R01,1,0,符合,1,a,2026-02-30','XW-R01,1,0,符合,1,,2026-09-12'])assert.throws(()=>parseBusinessCSV(header+bad,ids));assert.throws(()=>parseBusinessCSV(header+text.split('\n')[1]+'\n'+text.split('\n')[1],ids));});
const context={units,analyses,selectedId:'XW-R01',compared:['XW-R01','XW-R03'],scope:'unit',mode:'demo',profile:'balanced',runs:[],evidence};
test('conversation restricts implicit cross-unit queries and preserves missing evidence',()=>{assert.match(answerQuestion('XW-R03的空置率是多少',context).text,/范围之外/);assert.match(answerQuestion('锁金四村的空置率是多少',context).text,/范围之外/);assert.match(answerQuestion('空置率是多少',{...context,mode:'observed'}).text,/缺失|资料不足/);assert.match(answerQuestion('今天纽约天气怎么样',context).text,/没有支持/);});
test('local conversation gives scope-specific citations and explicit same-business action proposals',()=>{const a=answerQuestion('为什么值得关注？',context);assert(a.sources.some(s=>s.id==='U1'));assert(a.sources.some(s=>s.id==='R1'));assert.match(a.text,/虚构演示/);assert.equal(answerQuestion('运行评估',context).actions[0].type,'evaluate');assert.equal(answerQuestion('找出交通600米以内的居住单元',context).actions[0].filter.maxTransit,600);assert.match(answerQuestion('比较研究单元',{...context,scope:'compare'}).text,/锁金四村/);assert.match(answerQuestion('地价多少钱',context).text,/不输出.*市场价值/);});
test('report DOCX is an actual OOXML package with snapshot values, caveats and attribution',()=>{const run=createRun(units.find(u=>u.id==='XW-R01'),analyses.get('XW-R01'),{mode:'demo'}),model=reportModel(run,analyses.get('XW-R01'),{note:'<复核 & 讨论>',evidence});const bytes=reportDocx(model),zip=unzipSync(bytes),doc=strFromU8(zip['word/document.xml']);assert(zip['[Content_Types].xml']);assert(zip['_rels/.rels']);assert(doc.includes(run.id));assert(doc.includes('&lt;复核 &amp; 讨论&gt;'));assert(doc.includes('制作者：东南大学建筑学院 蔡子攀'));assert(doc.includes('虚构'));assert(doc.includes('未复核'));assert(doc.includes('UTM 50N'));assert.equal(model.run.total,run.total);assert(reportMarkdown(model).includes(String(run.total)));});
test('district switching intersects search and assessment state without deleting runs',()=>{
 const names=[['GL-R01','鼓楼区','320106'],['XW-R02','玄武区','320102'],['QX-R03','栖霞区','320113']];
 const fixture=names.map(([id,district_name,division_code])=>({...units[0],id,properties:{...units[0].properties,name:'共享社区',research_type:'居住社区',district_name,division_code}}));
 const studio=Object.create(ValueStudio.prototype),analysis=analyses.get(units[0].id);
 studio.units=fixture;studio.analyses=new Map(fixture.map(u=>[u.id,analysis]));studio.state={selected:fixture[0].id,mode:'demo',profile:'balanced',uploaded:{},runs:[createRun(fixture[0],analysis,{mode:'demo'})],filter:{query:'共享',type:'居住社区',status:'',maxTransit:null,district:''}};studio.render=()=>{};
 const saved=JSON.stringify(studio.state.runs);
 assert.deepEqual(studio.setDistrict('320102').map(u=>u.id),['XW-R02']);assert.equal(studio.current().id,'XW-R02');assert.equal(studio.state.filter.query,'共享');
 studio.state.filter.status='done';assert.equal(studio.visibleUnits().length,0);
 assert.deepEqual(studio.setDistrict('320106').map(u=>u.id),['GL-R01']);assert.equal(JSON.stringify(studio.state.runs),saved);
 studio.state.filter.status='';assert.equal(studio.setDistrict('all').length,3);assert.equal(studio.state.filter.district,'');studio.state.filter.query='栖霞';assert.deepEqual(studio.visibleUnits().map(u=>u.id),['QX-R03']);
});
test('imports accept six districts as a collection, feature array or geometry array and retain single-geometry compatibility',()=>{
 const definitions=[['鼓楼区','320106',118.7,32.08],['玄武区','320102',118.8,32.05],['秦淮区','320104',118.81,32.01],['雨花台区','320114',118.61,31.88],['建邺区','320105',118.66,31.95],['栖霞区','320113',119.21,32.15]];
 const square=(x,y,w=.02)=>({type:'Polygon',coordinates:[[[x,y],[x+w,y],[x+w,y+w],[x,y+w],[x,y]]]});
 const boundaries={type:'FeatureCollection',features:definitions.map(([district_name,division_code,x,y])=>({type:'Feature',properties:{district_name,division_code},geometry:square(x,y)}))};
 const input={type:'FeatureCollection',features:definitions.map(([,code,x,y])=>({type:'Feature',properties:{parcel_id:code},geometry:square(x+.005,y+.005,.002)}))};
 for(const boundary of [boundaries,boundaries.features,boundaries.features.map(f=>f.geometry),{type:'GeometryCollection',geometries:boundaries.features.map(f=>f.geometry)}])assert.equal(validateImport(input,boundary).features.length,6);
 const result=validateImport(input,boundaries);assert.deepEqual(result.features.map(f=>f.properties.division_code),definitions.map(d=>d[1]));assert.equal(validateImport({type:'FeatureCollection',features:[input.features[0]]},boundaries.features[0].geometry).features.length,1);
 const wrong=structuredClone(input);wrong.features[5].geometry=square(119.1,32.1,.002);assert.throws(()=>validateImport(wrong,boundaries),/研究区/);assert(!input.features[0].properties.district_name);
 const bounds=boundsOf(boundaries);assert.equal(bounds[0],118.61);assert.equal(bounds[1],31.88);assert(bounds[2]>119.23-.00001);
});
test('district-aware conversation protects cross-unit scope and does not label unrelated evidence as a local case',()=>{
 const qixia={...units[0],id:'QX-R01',properties:{...units[0].properties,name:'栖霞测试单元',district_name:'栖霞区',division_code:'320113'}};
 const ctx={...context,units:[...units,qixia],analyses:new Map([...analyses,[qixia.id,analyses.get(units[0].id)]])};
 assert.match(answerQuestion('QX-R01 的面积是多少',ctx).text,/范围之外/);
 const filtered=answerQuestion('找出栖霞区的居住单元',ctx);assert.equal(filtered.actions[0].filter.district,'320113');
 const cases=answerQuestion('有哪些鼓楼区更新案例？',{...ctx,evidence:{...evidence,documents:[{title:'玄武区更新案例',summary:'玄武区公开项目',date:'2026-09-12'}]}});assert.match(cases.text,/尚未收录/);assert.equal(cases.sources.length,0);
 const run=createRun(qixia,ctx.analyses.get(qixia.id),{mode:'demo'});assert.equal(run.districtName,'栖霞区');assert.match(reportModel(run,ctx.analyses.get(qixia.id)).subtitle,/栖霞区/);
});
test('saved camera validation covers southwest and east districts using the actual six-district extent',()=>{
 const bbox=[118.5843581,31.8676515,119.2395068,32.2470622],camera=center=>({center,zoom:11,bearing:0,pitch:48});
 assert(cameraInScope(camera([118.61,31.88]),bbox));assert(cameraInScope(camera([119.21,32.15]),bbox));assert(!cameraInScope(camera([116.4,39.9]),bbox));assert(!cameraInScope({...camera([118.8,32]),zoom:NaN},bbox));
});
