import {reportModel} from '../src/value-report.js';
import {FIELD_DEFS,evidenceBasis,VALIDITY,CONSTRAINTS,CONSTRAINT_STATUS} from '../src/assessment-evidence.js';
import {analyzeUnit,businessInput,createRun,normalizeAuxiliary,PROFILES,MODE_NAMES} from '../src/value-domain.js';
import {previewImport,resolveImport} from '../src/project-import.js';
import {loadStudyData} from './district-data.js';

class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new HttpError(status,message);};
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),json=JSON.stringify;
const validText=(v,max=120)=>typeof v==='string'&&v.trim()&&v.length<=max;
const stmt=(env,sql,...values)=>env.DB.prepare(sql).bind(...values);
const rows=async q=>(await q.all()).results;
const readObject=async(env,key)=>{const b=await env.BUCKET.get(key);if(!b)fail(503,'资料暂时不可读取，请稍后重试');return b.json();};
async function putObject(env,pid,kind,value){const key=`projects/${pid}/${kind}/${id()}.json`;await env.BUCKET.put(key,json(value),{httpMetadata:{contentType:'application/json'}});return key;}
async function body(request,max=10*1024*1024){if(Number(request.headers.get('content-length'))>max)fail(413,'文件或请求过大');const reader=request.body?.getReader();if(!reader)return {};let size=0,chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>max){await reader.cancel();fail(413,'文件或请求过大');}chunks.push(value);}const bytes=new Uint8Array(size);let at=0;for(const part of chunks){bytes.set(part,at);at+=part.length;}try{return JSON.parse(new TextDecoder().decode(bytes));}catch{fail(400,'请求内容格式无效');}}
async function identity(request,env){const uid=request.headers.get('oai-authenticated-user-id');if(!uid)fail(401,'请先登录再打开项目');let name=request.headers.get('oai-authenticated-user-full-name')||'';if(request.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8'){try{name=decodeURIComponent(name);}catch{name='';}}const email=request.headers.get('oai-authenticated-user-email')||'';await stmt(env,'INSERT INTO users (id,email,name,created_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name',uid,email,name||email||'用户',now()).run();return {id:uid,email,name:name||email||'用户'};}
async function project(env,pid,user,write=false,admin=false){const p=await stmt(env,'SELECT p.*,m.role FROM projects p JOIN members m ON m.project_id=p.id WHERE p.id=? AND m.user_id=?',pid,user.id).first();if(!p)fail(404,'项目不存在或未获授权');if(admin&&p.role!=='admin'||write&&p.role==='viewer')fail(403,'当前角色没有修改权限');if(write&&p.status==='archived')fail(409,'项目已归档，请管理员先恢复');return p;}
const publicProject=p=>{const {state,...other}=p;return {...other,state:JSON.parse(state||'{}')};};
async function dataAt(env,p,version=p.data_version){const v=await stmt(env,'SELECT * FROM data_versions WHERE project_id=? AND version=?',p.id,version).first();if(!v)fail(404,'数据版本不存在');return {version:v,data:await readObject(env,v.object_key)};}
const expected=(p,b)=>{if(!Number.isInteger(b.revision)||b.revision!==p.revision)fail(409,'项目已由其他窗口或成员修改。请重新载入并核对后提交，当前修改尚未保存。');};
async function commit(env,p,user,kind,summary,operations=[],update={}){
 const rev=p.revision+1,t=now();const qs=[stmt(env,'INSERT INTO events (id,project_id,revision,kind,summary,actor_id,actor_name,created_at) VALUES (?,?,?,?,?,?,?,?)',id(),p.id,rev,kind,summary,user.id,user.name,t),...operations,stmt(env,'UPDATE projects SET revision=?,data_version=?,state=?,status=?,name=?,description=?,updated_at=? WHERE id=? AND revision=?',rev,update.dataVersion??p.data_version,update.state?json(update.state):p.state,update.status??p.status,update.name??p.name,update.description??p.description,t,p.id,p.revision)];
 try{await env.DB.batch(qs);}catch(e){if(/UNIQUE|constraint/i.test(e.message))fail(409,'项目版本冲突，请重新载入后核对；未覆盖其他人的修改。');throw e;}return {revision:rev,dataVersion:update.dataVersion??p.data_version};
}
async function artifact(env,p,aid,kind){const a=await stmt(env,'SELECT * FROM artifacts WHERE project_id=? AND id=?',p.id,aid).first();if(!a||kind&&a.kind!==kind)fail(404,'记录不存在或未获授权');return a;}
async function addRecord(env,p,user,kind,value,name,metadata={},dataVersion=p.data_version){const key=await putObject(env,p.id,kind,value),aid=value.id||id();return {id:aid,query:stmt(env,'INSERT INTO artifacts (id,project_id,kind,name,object_key,data_version,metadata,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)',aid,p.id,kind,name,key,dataVersion,json(metadata),user.id,now())};}
async function staticJSON(env,path,origin){const response=await env.ASSETS.fetch(new Request(origin+'/'+path));if(!response.ok)fail(503,'基础空间资料暂不可用');return response.json();}
async function assessmentData(env,origin){return loadStudyData(p=>staticJSON(env,p,origin),async p=>{const response=await env.ASSETS.fetch(new Request(origin+'/'+p));if(!response.ok)fail(503,'基础空间资料暂不可用');return response.text();});}
const decode=s=>{try{return decodeURIComponent(s);}catch{fail(400,'地址无效');}};
export async function projectAPI(request,env){
 const url=new URL(request.url),headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Vary':'oai-authenticated-user-id'},reply=(v,status=200)=>new Response(json(v),{status,headers});
 try{
  if(!env.DB||!env.BUCKET)fail(503,'项目服务尚未连接，请稍后重试');
  if(!['GET','HEAD'].includes(request.method)){const origin=request.headers.get('origin');if(origin&&origin!==url.origin||request.headers.get('sec-fetch-site')==='cross-site')fail(403,'请求来源无效');if(!request.headers.get('content-type')?.startsWith('application/json'))fail(415,'请使用 JSON 请求');}
  const user=await identity(request,env),path=url.pathname.replace(/\/$/,'').split('/').slice(2).map(decode),method=request.method;
  if(path[0]==='me'&&method==='GET')return reply({user});
  if(path[0]!=='projects')fail(404,'接口不存在');
  if(path.length===1){
   if(method==='GET'){const projects=await rows(stmt(env,'SELECT p.*,m.role,(SELECT count(*) FROM artifacts a WHERE a.project_id=p.id AND a.kind=\'run\') AS run_count FROM projects p JOIN members m ON p.id=m.project_id WHERE m.user_id=? ORDER BY p.updated_at DESC',user.id));return reply({user,projects:projects.map(publicProject)});}
   if(method==='POST'){
    const b=await body(request);if(!validText(b.name)||typeof b.description!=='string'||b.description.length>1000)fail(400,'请填写项目名称，说明不超过 1,000 字');
    const pid=id(),t=now(),units=b.template==='xuanwu'?(await staticJSON(env,'data/research-units.geojson',url.origin)).features:[];
    const data={units,uploaded:{},housing:[]},key=await putObject(env,pid,'data',data);
    await env.DB.batch([stmt(env,'INSERT INTO projects (id,name,description,status,owner_id,revision,data_version,state,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)',pid,b.name.trim(),b.description.trim(),'active',user.id,1,1,'{}',t,t),stmt(env,'INSERT INTO members (project_id,user_id,role) VALUES (?,?,?)',pid,user.id,'admin'),stmt(env,'INSERT INTO data_versions (id,project_id,version,object_key,summary,created_by,created_at) VALUES (?,?,?,?,?,?,?)',id(),pid,1,key,units.length?'从玄武公开研究范围建立':'建立空项目',user.id,t),stmt(env,'INSERT INTO events (id,project_id,revision,kind,summary,actor_id,actor_name,created_at) VALUES (?,?,?,?,?,?,?,?)',id(),pid,1,'create','建立项目',user.id,user.name,t)]);
    return reply({id:pid},201);
   }fail(405,'不支持此操作');
  }
  const pid=path[1],route=path[2]||'',write=!['GET','HEAD'].includes(method),p=await project(env,pid,user,write&&route!=='archive',route==='members'&&write||route==='archive'&&write);
  if(!route&&method==='GET'){
   const {data}=await dataAt(env,p),artifacts=await rows(stmt(env,'SELECT id,kind,name,data_version,metadata,created_by,created_at FROM artifacts WHERE project_id=? ORDER BY created_at',pid));
   const runArtifacts=artifacts.filter(a=>a.kind==='run'),runs=[];for(let i=0;i<runArtifacts.length;i+=12)runs.push(...await Promise.all(runArtifacts.slice(i,i+12).map(async a=>readObject(env,(await artifact(env,p,a.id)).object_key))));
   const reviews=[];for(const a of artifacts.filter(a=>a.kind==='review'))reviews.push(await readObject(env,(await artifact(env,p,a.id)).object_key));return reply({project:publicProject(p),data,artifacts,runs,reviews,user});
  }
  if(route==='state'&&method==='POST'){const b=await body(request,500000);expected(p,b);const s=b.state||{};if(!MODE_NAMES[s.mode]||!PROFILES[s.profile]||!Array.isArray(s.compared)||s.compared.length>3||!Array.isArray(s.history)||s.history.length>100)fail(400,'研究状态无效');const scenario=s.scenario;if(!scenario||!Number.isFinite(scenario.far)||scenario.far<.1||scenario.far>6||!Number.isFinite(scenario.retain)||scenario.retain<0||scenario.retain>100||!Number.isFinite(scenario.publicShare)||scenario.publicShare<0||scenario.publicShare>80)fail(400,'情景参数无效');if(s.history.some(m=>!m||typeof m.question!=='string'||m.question.length>1200||typeof m.context!=='string'||!MODE_NAMES[m.mode]||!validText(m.date,80)||typeof m.answer?.text!=='string'||m.answer.text.length>30000||!Array.isArray(m.answer.sources)||!Array.isArray(m.answer.actions)||m.answer.sources.some(x=>!x||typeof x.id!=='string'||typeof x.title!=='string'||typeof x.text!=='string')||m.answer.actions.some(x=>!x||typeof x.type!=='string'||typeof x.label!=='string')))fail(400,'研究记录格式无效');const {data}=await dataAt(env,p);if(s.compared.some(uid=>!data.units.some(u=>u.id===uid))||s.selected&&!data.units.some(u=>u.id===s.selected))fail(400,'研究对象不属于本项目');let auxiliary;try{auxiliary=normalizeAuxiliary(s.auxiliary);}catch(e){fail(400,e.message);}const state={auxiliary,workflowVersion:['studio14','studio15'].includes(s.workflowVersion)?s.workflowVersion:undefined,selected:s.selected,mode:s.mode,profile:s.profile,compared:s.compared,history:s.history,scenario:s.scenario};return reply(await commit(env,p,user,'state','更新研究口径、比较清单或研究记录',[],{state}));}
  if(route==='archive'&&method==='POST'){const b=await body(request);expected(p,b);if(!['active','archived'].includes(b.status))fail(400,'归档状态无效');return reply(await commit(env,p,user,'archive',b.status==='archived'?'归档项目':'恢复归档项目',[],{status:b.status}));}
  if(route==='metadata'&&method==='POST'){const b=await body(request);expected(p,b);if(!validText(b.name)||typeof b.description!=='string'||b.description.length>1000)fail(400,'项目名称或说明无效');return reply(await commit(env,p,user,'metadata','修改项目名称与说明',[],{name:b.name.trim(),description:b.description.trim()}));}
  if(route==='data'&&path[3]==='clear'&&method==='POST'){const b=await body(request);expected(p,b);if(!['ledger','boundaries'].includes(b.kind))fail(400,'数据类型无效');const {data}=await dataAt(env,p);if(b.kind==='ledger')data.uploaded={};else{const ids=data.units.filter(u=>u.properties.imported).map(u=>u.id);data.units=data.units.filter(u=>!ids.includes(u.id));data.uploaded=Object.fromEntries(Object.entries(data.uploaded).filter(([uid])=>!ids.includes(uid)));}const next=p.data_version+1,key=await putObject(env,pid,'data',data),summary=b.kind==='ledger'?'清空当前台账':'移除当前导入边界';return reply(await commit(env,p,user,'data',summary,[stmt(env,'INSERT INTO data_versions (id,project_id,version,object_key,summary,created_by,created_at) VALUES (?,?,?,?,?,?,?)',id(),pid,next,key,summary,user.id,now())],{dataVersion:next}));}
  if(route==='members'){
   if(method==='GET'){if(p.role!=='admin')fail(403,'仅管理员可查看成员管理');return reply({members:await rows(stmt(env,'SELECT m.user_id,m.role,u.name,u.email FROM members m JOIN users u ON m.user_id=u.id WHERE m.project_id=?',pid))});}
   if(method==='POST'){const b=await body(request);expected(p,b);if(!validText(b.userId,200)||!['admin','editor','viewer','remove'].includes(b.role))fail(400,'成员或角色无效');if(b.userId===p.owner_id)fail(400,'项目创建者的管理员权限保留');if(!await stmt(env,'SELECT id FROM users WHERE id=?',b.userId).first())fail(400,'未找到此账户，请对方先登录本站并复制账户编号');const operation=b.role==='remove'?stmt(env,'DELETE FROM members WHERE project_id=? AND user_id=?',pid,b.userId):stmt(env,'INSERT INTO members (project_id,user_id,role) VALUES (?,?,?) ON CONFLICT(project_id,user_id) DO UPDATE SET role=excluded.role',pid,b.userId,b.role);return reply(await commit(env,p,user,'member',`设置成员 ${b.userId}：${b.role}`,[operation]));}
  }
  if(route==='history'&&method==='GET')return reply({versions:await rows(stmt(env,'SELECT id,version,summary,created_by,created_at FROM data_versions WHERE project_id=? ORDER BY version DESC',pid)),events:await rows(stmt(env,'SELECT * FROM events WHERE project_id=? ORDER BY revision DESC LIMIT 300',pid))});
  if(route==='versions'&&method==='GET'){const v=Number(path[3]);if(!Number.isInteger(v))fail(400,'版本无效');return reply(await dataAt(env,p,v));}
  if(route==='restore'&&method==='POST'){const b=await body(request);expected(p,b);if(!Number.isInteger(b.version)||b.version<1)fail(400,'版本无效');const {data}=await dataAt(env,p,b.version),key=await putObject(env,pid,'data',data),next=p.data_version+1;return reply(await commit(env,p,user,'restore',`恢复数据 V${b.version} 为新版本 V${next}`,[stmt(env,'INSERT INTO data_versions (id,project_id,version,object_key,summary,created_by,created_at) VALUES (?,?,?,?,?,?,?)',id(),pid,next,key,`恢复 V${b.version}`,user.id,now())],{dataVersion:next}));}
  if(route==='imports'&&path[3]==='preflight'&&method==='POST'){
   const b=await body(request);expected(p,b);const {data}=await dataAt(env,p),{boundary}=await assessmentData(env,url.origin),preview=previewImport(b,data,boundary);
   const token=id(),key=await putObject(env,pid,'imports',{...preview,original:{name:b.name,text:b.text,mapping:b.mapping,areaUnit:b.areaUnit,vacancyUnit:b.vacancyUnit}});await stmt(env,'INSERT INTO preflights (id,project_id,actor_id,revision,object_key,expires_at,committed) VALUES (?,?,?,?,?,?,0)',token,pid,user.id,p.revision,key,new Date(Date.now()+3600000).toISOString()).run();const {candidate,...summary}=preview;return reply({...summary,token,revision:p.revision});
  }
  if(route==='imports'&&path[3]==='commit'&&method==='POST'){
   const b=await body(request),pre=await stmt(env,'SELECT * FROM preflights WHERE id=? AND project_id=? AND actor_id=?',b.token,pid,user.id).first();if(!pre)fail(404,'预检不存在');if(pre.committed)return reply({revision:p.revision,dataVersion:p.data_version,alreadyCommitted:true});expected(p,b);if(pre.revision!==p.revision)fail(409,'预检后项目已变化，请重新预检');if(pre.expires_at<now())fail(410,'预检已过期，请重新预检');
   const preview=await readObject(env,pre.object_key);let data;try{data=resolveImport(preview,b.decisions);}catch(e){fail(422,e.message);}const next=p.data_version+1,key=await putObject(env,pid,'data',data),resolution=await putObject(env,pid,'import-resolutions',{preview,decisions:b.decisions,dataVersion:next,actor:user.id,at:now()}),aid=id();
   const result=await commit(env,p,user,'import',`导入 ${preview.count} 条 ${preview.kind}；${preview.conflicts.length} 条来源冲突已处理`,[stmt(env,'INSERT INTO data_versions (id,project_id,version,object_key,summary,created_by,created_at) VALUES (?,?,?,?,?,?,?)',id(),pid,next,key,`导入 ${preview.original.name||preview.kind}`,user.id,now()),stmt(env,'UPDATE preflights SET committed=1 WHERE id=?',b.token),stmt(env,'INSERT INTO artifacts (id,project_id,kind,name,object_key,data_version,metadata,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)',aid,pid,'import',preview.original.name||'导入记录',resolution,next,json({conflicts:preview.conflicts.length}),user.id,now())],{dataVersion:next});return reply(result);
  }
  if(route==='evidence'&&method==='POST'){
   const b=await body(request,100000);expected(p,b);const {data}=await dataAt(env,p);if(!data.units.some(u=>u.id===b.unitId))fail(404,'研究对象不属于本项目');if(!MODE_NAMES[b.mode])fail(400,'评估口径无效');const unit=data.units.find(u=>u.id===b.unitId),base=await assessmentData(env,url.origin),analysis=analyzeUnit(unit,base.data,base.services),input=businessInput(unit,analysis,b.mode,data.uploaded),geometry=JSON.stringify(unit.geometry),record={fields:{},constraints:{},recordVersion:p.data_version+1,geometry};
   const refs=async list=>{if(!Array.isArray(list)||list.length>5)fail(400,'每项最多引用 5 页');const output=[];for(const ref of list){if(!ref||!validText(ref.documentId,200)||!Number.isInteger(ref.page)||ref.page<1)fail(400,'页码引用无效');const doc=await readObject(env,(await artifact(env,p,ref.documentId,'document')).object_key),page=doc.pages.find(x=>x.page===ref.page);if(!page)fail(422,'引用页不存在');output.push({documentId:doc.id,attachmentId:doc.attachmentId,page:ref.page,title:doc.name,text:page.text.slice(0,1200),extraction:doc.extraction});}return output;};
   const validDate=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d;
   for(const [key] of FIELD_DEFS){const f=b.fields?.[key];if(!f)continue;if(!validText(f.source,300)||!validDate(f.date)||!VALIDITY[f.validity]||!['unverified','verified'].includes(f.verification)||typeof f.reason!=='string'||f.reason.length>500)fail(400,'请核对逐项来源、日期和状态');const spatial=['area','distance'].includes(key),basis=evidenceBasis(input,analysis,{mode:b.mode,geometry},key);record.fields[key]={basis,source:f.source,date:f.date,validity:f.validity,verification:f.verification,reason:f.reason,refs:await refs(f.refs||[]),recordedBy:user.id,recordedByName:user.name,recordedAt:now()};}
   for(const category of Object.keys(CONSTRAINTS)){const c=b.constraints?.[category]||{status:'unknown',summary:'',refs:[],date:null};if(!CONSTRAINT_STATUS[c.status]||typeof c.summary!=='string'||c.summary.length>1000||c.date&&!validDate(c.date))fail(400,'约束资料无效');const references=await refs(c.refs||[]);if(c.status!=='unknown'&&(!c.summary.trim()||!references.length||!c.date))fail(422,'发现事项或已核对需填写说明、日期并引用附件页');record.constraints[category]={status:c.status,summary:c.summary,date:c.date||null,refs:references,recordedBy:user.id,recordedByName:user.name,recordedAt:now()};}
   data.evidence={...data.evidence,[b.unitId]:record};const next=p.data_version+1,key=await putObject(env,pid,'data',data);return reply(await commit(env,p,user,'evidence','更新逐项依据与独立约束',[stmt(env,'INSERT INTO data_versions (id,project_id,version,object_key,summary,created_by,created_at) VALUES (?,?,?,?,?,?,?)',id(),pid,next,key,'更新依据：'+b.unitId,user.id,now())],{dataVersion:next}));
  }
  if(route==='documents'&&method==='GET'){const documents=[];for(const a of await rows(stmt(env,"SELECT * FROM artifacts WHERE project_id=? AND kind='document' ORDER BY created_at",pid)))documents.push(await readObject(env,a.object_key));return reply({documents});}
  if(route==='reviews'&&method==='POST'){
   const b=await body(request,10000);expected(p,b);if(!['reviewed','changes'].includes(b.status)||!validText(b.note,2000))fail(400,'请选择复核结论并填写意见');const run=await readObject(env,(await artifact(env,p,b.runId,'run')).object_key);if(run.projectDataVersion!==p.data_version)fail(409,'数据已更新，请重算后复核');const review={id:id(),projectId:pid,runId:run.id,status:b.status,note:b.note,actorId:user.id,actorName:user.name,reviewedAt:now()};const record=await addRecord(env,p,user,'review',review,'复核：'+run.name,{runId:run.id,status:b.status},run.projectDataVersion);return reply({...await commit(env,p,user,'review','记录项目内复核：'+run.name,[record.query]),review});
  }
  if(route==='evaluate'&&method==='POST'){
   const b=await body(request);expected(p,b);if(!Array.isArray(b.unitIds)||!b.unitIds.length||b.unitIds.length>3||new Set(b.unitIds).size!==b.unitIds.length||!PROFILES[b.profile]||!MODE_NAMES[b.mode])fail(400,'请选择有效的地块与评估口径');const {data}=await dataAt(env,p);if(b.unitIds.some(uid=>!data.units.some(u=>u.id===uid)))fail(404,'研究对象不属于本项目');let auxiliary;try{auxiliary=normalizeAuxiliary(b.auxiliary);}catch(e){fail(400,e.message);}const base=await assessmentData(env,url.origin),runs=[],operations=[];
   for(const uid of b.unitIds){const unit=data.units.find(u=>u.id===uid),analysis=analyzeUnit(unit,base.data,base.services);const run={...createRun(unit,analysis,{mode:b.mode,profile:b.profile,uploaded:data.uploaded,evidenceRecords:data.evidence||{},populationGrid:base.data.populationGrid,housing:data.housing||[],auxiliary}),id:id(),projectId:pid,projectDataVersion:p.data_version,createdBy:user.id,createdByName:user.name,geometry:unit.geometry};runs.push(run);operations.push((await addRecord(env,p,user,'run',run,run.name,{unitId:uid,mode:b.mode,profile:b.profile,total:run.total})).query);}
   const result=await commit(env,p,user,'evaluate',`保存 ${runs.length} 次评估，基于数据 V${p.data_version}`,operations);return reply({...result,runs});
  }
  if(route==='artifacts'&&path[3]&&method==='GET'){
   const a=await artifact(env,p,path[3]),blob=await env.BUCKET.get(a.object_key);if(!blob)fail(503,'附件暂时不可读取');if(a.kind==='attachment'){const meta=JSON.parse(a.metadata);return new Response(blob.body,{headers:{'Content-Type':meta.mime||'application/octet-stream','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(a.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}return reply({artifact:{...a,object_key:undefined},value:await blob.json()});
  }
  if(route==='attachments'&&method==='POST'){
   const b=await body(request,8*1024*1024);expected(p,b);if(!validText(b.name,200)||typeof b.base64!=='string'||!['application/pdf','text/plain'].includes(b.mime))fail(400,'支持 PDF / TXT，单个文件限 5 MB');let bytes;try{bytes=Uint8Array.from(atob(b.base64),c=>c.charCodeAt(0));}catch{fail(400,'文件编码无效');}if(bytes.length>5*1024*1024)fail(413,'附件超过 5 MB');if(b.mime==='application/pdf'&&new TextDecoder().decode(bytes.slice(0,5))!=='%PDF-')fail(400,'文件内容不是有效 PDF');
   let pages,extraction;if(b.mime==='text/plain'){let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);}catch{fail(422,'TXT 请使用 UTF-8 编码');}pages=text.split('\f').map((text,i)=>({page:i+1,text}));extraction='原始 TXT；分页符分页，无分页符为第 1 页';}else{if(!Array.isArray(b.pages)||!b.pages.length||b.pages.length>200||b.pages.some((x,i)=>x.page!==i+1||typeof x.text!=='string'||x.text.length>100000))fail(422,'PDF 文本页索引无效，最多 200 页');pages=b.pages;extraction='PDF.js 客户端提取，需对照原文核实；未执行 OCR';}if(pages.reduce((n,x)=>n+x.text.length,0)>1500000)fail(413,'文档文本超过 150 万字符');
   const aid=id(),key=`projects/${pid}/attachments/${aid}`,sha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),n=>n.toString(16).padStart(2,'0')).join('');await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:b.mime}});const doc={id:id(),attachmentId:aid,name:b.name,pages,extraction,sha256,sourceDate:typeof b.sourceDate==='string'?b.sourceDate.slice(0,10):null,createdAt:now()},indexed=await addRecord(env,p,user,'document',doc,b.name,{attachmentId:aid,pages:pages.length});const result=await commit(env,p,user,'attachment',`上传附件：${b.name}`,[stmt(env,'INSERT INTO artifacts (id,project_id,kind,name,object_key,data_version,metadata,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)',aid,pid,'attachment',b.name,key,p.data_version,json({size:bytes.length,mime:b.mime,documentId:doc.id,sha256}),user.id,now()),indexed.query]);return reply({...result,id:aid,documentId:doc.id});
  }
  if(route==='reports'&&method==='POST'){
   const b=await body(request,8*1024*1024);expected(p,b);const m=b.model;if(!m||!validText(m.run?.id,200)||!Array.isArray(m.sections)||m.sections.length>30)fail(400,'报告快照无效');const a=await artifact(env,p,m.run.id,'run'),savedRun=await readObject(env,a.object_key);if(json(m.run)!==json(savedRun))fail(422,'报告必须引用未修改的已保存评估');if(typeof m.mapImage!=='string'||!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(m.mapImage)||m.mapImage.length>5*1024*1024)fail(422,'报告地图应为有效 PNG 快照');
   if(m.id){const existing=await stmt(env,'SELECT id FROM artifacts WHERE id=? AND project_id=? AND kind=\'report\'',m.id,pid).first();if(existing){const old=await readObject(env,(await artifact(env,p,m.id)).object_key);if(json(old)!==json(m))fail(409,'已保存报告不能覆盖，请另存新版本');return reply({revision:p.revision,model:old});}}
   let revision=1,familyId=id(),parentId=null;if(b.parentId){const parent=await readObject(env,(await artifact(env,p,b.parentId,'report')).object_key);familyId=parent.familyId;const latest=await stmt(env,"SELECT MAX(CAST(json_extract(metadata,'$.revision') AS INTEGER)) AS latest FROM artifacts WHERE project_id=? AND kind='report' AND json_extract(metadata,'$.familyId')=?",pid,familyId).first();revision=Math.max(parent.revision,latest?.latest||1)+1;parentId=parent.id;}
   if(typeof m.note!=='string'&&m.note!==undefined||String(m.note||'').length>2000)fail(400,'研究叙述最多 2,000 字');
   const comparison=[];if(!Array.isArray(m.comparison||[])||(m.comparison||[]).length>3)fail(400,'比较引用无效');for(const candidate of m.comparison||[])comparison.push(await readObject(env,(await artifact(env,p,candidate.id,'run')).object_key));
   let review=null;if(m.reviewId){const claimed=await readObject(env,(await artifact(env,p,m.reviewId,'review')).object_key);if(claimed.runId!==savedRun.id)fail(422,'复核记录不属于此评估');}const latestReview=await stmt(env,"SELECT * FROM artifacts WHERE project_id=? AND kind='review' AND json_extract(metadata,'$.runId')=? ORDER BY created_at DESC,rowid DESC LIMIT 1",pid,savedRun.id).first();if(latestReview)review=await readObject(env,latestReview.object_key);
   const canonical=reportModel(savedRun,savedRun.analysisSnapshot||{area:savedRun.input.area,buildingCount:0,nearest:{},method:'旧版运行未保存完整空间分析'}, {note:m.note||'',comparison,review});
   const model={...canonical,mapImage:m.mapImage,id:id(),projectId:pid,projectDataVersion:a.data_version,run:savedRun,familyId,parentId,revision,createdBy:user.id,createdByName:user.name,createdAt:now()};const record=await addRecord(env,p,user,'report',model,model.subtitle||savedRun.name,{runId:savedRun.id,familyId,revision},a.data_version);const result=await commit(env,p,user,'report',`保存报告 V${revision}：${savedRun.name}`,[record.query]);return reply({...result,model});
  }
  if(route==='comparisons'&&method==='POST'){
   const b=await body(request);expected(p,b);if(!Array.isArray(b.runIds)||b.runIds.length<2||b.runIds.length>3||new Set(b.runIds).size!==b.runIds.length||!['units','history'].includes(b.type))fail(400,'请选择 2–3 次已保存评估');if(b.baselineRunId&&!b.runIds.includes(b.baselineRunId))fail(400,'比较基准必须属于所选评估');const runs=[];for(const rid of b.runIds)runs.push(await readObject(env,(await artifact(env,p,rid,'run')).object_key));if(b.type==='history'&&(runs.length!==2||runs[0].unitId!==runs[1].unitId))fail(400,'历史比较应选择同一地块的两个评估版本');if(b.type==='units'&&new Set(runs.map(r=>r.unitId)).size!==runs.length)fail(400,'地块比较请选择不同地块');const snapshot={id:id(),baselineRunId:b.runIds.includes(b.baselineRunId)?b.baselineRunId:b.runIds[0],type:b.type,projectId:pid,createdAt:now(),createdBy:user.name,runIds:b.runIds,runs};const record=await addRecord(env,p,user,'comparison',snapshot,b.type==='history'?'历史评估比较':'研究单元比较',{type:b.type,runIds:b.runIds});const result=await commit(env,p,user,'comparison','保存固定评估版本的比较快照',[record.query]);return reply({...result,snapshot});
  }
  fail(404,'接口不存在');
 }catch(e){if(!e.status)console.error('Project service:',e.message);return reply({error:e.status?e.message:'项目服务暂不可用，未确认保存，请重试',code:e.status||503},e.status||503);}
}
export default {async fetch(request,env){const path=new URL(request.url).pathname;if(path.startsWith('/api/'))return projectAPI(request,env);if(path.startsWith('/server/')||path.startsWith('/.openai/'))return new Response('Not found',{status:404});return env.ASSETS.fetch(request);}};
