import {EMPTY,centerOf} from './geo.js';
export const THEMES={
 day:{bg:'#f3f5f6',green:'#d1e1c7',civic:'#dbe8ed',residential:'#e9e9ed',commercial:'#eee4db',industrial:'#e5e2eb',other:'#e4e8ed',water:'#b6d8e8',shore:'#8cb6cb',road:'#ffffff',case:'#d9dfe4',rail:'#a193b4',text:'#536a80',halo:'#ffffff',known:'#bcad97',levels:'#9dbed3',unknown:'#d1d8e2',boundary:'#86a4bf',shadow:'#6a8999',sky:'#e7f2fb'},
 night:{bg:'#111e34',green:'#244b48',civic:'#2b4356',residential:'#2b3a55',commercial:'#594b56',industrial:'#454267',other:'#293c52',water:'#184663',shore:'#417f98',road:'#8dabc3',case:'#172a40',rail:'#be9cdf',text:'#bfd7ea',halo:'#15253d',known:'#d7bc8a',levels:'#83c3d1',unknown:'#637d9c',boundary:'#91cdbc',shadow:'#060f24',sky:'#182d47'},
 ink:{bg:'#f1f0e5',green:'#d3dcc7',civic:'#e1e0d3',residential:'#edebdf',commercial:'#e5dfcb',industrial:'#e1dedc',other:'#e7e4d5',water:'#bdcfc9',shore:'#a2b6ae',road:'#fffef7',case:'#d8d4c3',rail:'#9faaa0',text:'#657564',halo:'#faf9f0',known:'#b5ae98',levels:'#a2bdb7',unknown:'#dfdcd0',boundary:'#7f967c',shadow:'#7f8c75',sky:'#f0f0e6'}
};
export function makeStyle(data,{theme='day',mode='3d',terrain=true,schematic=true,layers={}},base) {
 const c=THEMES[theme],sources={};
 for(const id of ['boundary','land','water','roads','buildings','pois'])sources[id]={type:'geojson',data:data[id],maxzoom:17,tolerance:.45};
 for(const id of ['districtFocus','selected','imported','measure','research','studySelected','context','radius','population'])sources[id]={type:'geojson',data:EMPTY()};
 sources.landmarkLabels={type:'geojson',data:{type:'FeatureCollection',features:data.buildings.features.filter(f=>f.properties.visual_landmark).map(f=>({type:'Feature',properties:{name:f.properties.visual_landmark},geometry:{type:'Point',coordinates:centerOf(f.geometry)}}))}};
 sources.districtLabels={type:'geojson',data:{type:'FeatureCollection',features:data.boundary.features.map(f=>({type:'Feature',properties:f.properties,geometry:{type:'Point',coordinates:centerOf(f.geometry)}}))}};
 const dem={type:'raster-dem',tiles:[`${base}data/terrain/{z}/{x}/{y}.png`],encoding:'terrarium',tileSize:256,minzoom:12,maxzoom:12,bounds:[118.72,31.98,118.96,32.15]};
 sources.dem={...dem};sources.hillshade={...dem};
 const style={version:8,name:`UrbanLens Nanjing / ${theme}`,glyphs:'local-font://{fontstack}/{range}.pbf',sources,light:{anchor:'map',color:theme==='night'?'#fdeac5':'#fff8e9',intensity:.34,position:[1.2,220,32]},sky:{'sky-color':c.sky,'horizon-color':c.bg,'fog-color':c.bg,'sky-horizon-blend':.7,'horizon-fog-blend':.7,'fog-ground-blend':.6},layers:[]};
 if(mode==='3d'&&terrain)style.terrain={source:'dem',exaggeration:1};
 const add=(id,type,source,paint,filter,layout={},group=source)=>style.layers.push({id,type,...(source?{source}:{}),...(filter?{filter}:{}),layout:{...layout,visibility:layers[group]===false?'none':'visible'},paint});
 const eq=(p,v)=>['==',['get',p],v];
 add('background','background',null,{'background-color':c.bg});
 add('district-tint','fill','boundary',{'fill-color':theme==='night'?'#20334a':'#f2f7fc','fill-opacity':.25});
 add('land','fill','land',{'fill-color':['match',['get','category'],'green',c.green,'civic',c.civic,'residential',c.residential,'commercial',c.commercial,'industrial',c.industrial,c.other],'fill-opacity':.93});
 add('land-outline','line','land',{'line-color':theme==='night'?'#65816a':'#bac8b2','line-opacity':['interpolate',['linear'],['zoom'],12,.08,16,.26],'line-width':.5});
 add('hills','hillshade','hillshade',{'hillshade-shadow-color':c.shadow,'hillshade-highlight-color':theme==='night'?'#5c7761':'#ffffe4','hillshade-accent-color':c.shadow,'hillshade-exaggeration':.22,'hillshade-illumination-direction':315},null,{},'terrain');
 add('water','fill','water',{'fill-color':c.water,'fill-opacity':1});
 add('water-edge','line','water',{'line-color':c.shore,'line-width':['interpolate',['linear'],['zoom'],11,.5,15,1.1,18,1.7],'line-opacity':.55});
 const roadFilter=['all',eq('category','road'),['!=',['get','underground'],true]];
 const width=['interpolate',['linear'],['zoom'],11,['match',['get','road_class'],'major',1.4,'secondary',.6,.12],14,['match',['get','road_class'],'major',4.4,'secondary',2.7,'path',.5,1.1],18,['match',['get','road_class'],'major',28,'secondary',19,'path',3,7]];
 const casing=structuredClone(width);for(const i of [4,6,8])casing[i]=['*',casing[i],1.3];
 add('roads-case','line','roads',{'line-color':c.case,'line-width':casing},roadFilter,{'line-cap':'round','line-join':'round'});
 add('roads','line','roads',{'line-color':theme==='day'?['match',['get','road_class'],'major','#f4e9c8',c.road]:c.road,'line-width':width},roadFilter,{'line-cap':'round','line-join':'round'});
 add('tunnels','line','roads',{'line-color':c.case,'line-width':['interpolate',['linear'],['zoom'],12,.7,17,4],'line-dasharray':[2,2],'line-opacity':.7},['all',eq('category','road'),eq('underground',true)]);
 add('rail','line','roads',{'line-color':c.rail,'line-width':['interpolate',['linear'],['zoom'],11,1,17,3],'line-opacity':.8},eq('category','rail'),{},'rail');
 add('rail-sleepers','line','roads',{'line-color':c.road,'line-width':1,'line-dasharray':[1,3],'line-opacity':.65},eq('category','rail'),{},'rail');
 add('waterways','line','roads',{'line-color':c.water,'line-width':['interpolate',['linear'],['zoom'],11,1,17,6]},eq('category','waterway'),{},'water');
 add('population-fill','fill','population',{'fill-color':'#8eb7d2','fill-opacity':.58},null,{},'population');
 const color=['coalesce',['get',`appearance_${theme}`],['match',['get','height_source'],'osm',c.known,'levels',c.levels,c.unknown]];
 add('building-footprints','fill','buildings',{'fill-color':color,'fill-opacity':['interpolate',['linear'],['zoom'],11,.52,14,.78,17,.92]});
 add('building-edges','line','buildings',{'line-color':theme==='night'?'#84947c':'#b3b5a5','line-opacity':['interpolate',['linear'],['zoom'],12,.10,15,.3,18,.5],'line-width':['interpolate',['linear'],['zoom'],12,.25,18,.7]});
 add('building-3d','fill-extrusion','buildings',{'fill-extrusion-color':color,'fill-extrusion-height':mode==='2d'?0:schematic?['get','render_height']:['coalesce',['get','height_m'],0],'fill-extrusion-base':mode==='2d'?0:['get','render_base'],'fill-extrusion-opacity':1,'fill-extrusion-vertical-gradient':true});
 add('district-focus','line','districtFocus',{'line-color':'#0071e3','line-width':3,'line-opacity':.85});
 add('district-border','line','boundary',{'line-color':c.boundary,'line-width':1.1,'line-dasharray':[5,4],'line-opacity':.5});
 const catColor=['match',['get','category'],'education','#659b92','health','#c97b70','transport',c.rail,'culture','#b29967','nature','#6e9361','#9ea594'];
 const poiPaint={'circle-color':catColor,'circle-radius':['interpolate',['linear'],['zoom'],12,1.5,16,4],'circle-stroke-color':c.halo,'circle-stroke-width':1,'circle-opacity':['step',['zoom'],.3,14,.9]};
 add('poi-dots','circle','pois',poiPaint,['all',['!=',['get','category'],'place'],['!=',['get','category'],'transport']]);
 add('station-dots','circle','pois',poiPaint,eq('category','transport'),{},'rail');
 const textPaint={'text-color':c.text,'text-halo-color':c.halo,'text-halo-width':1.5,'text-halo-blur':.4};
 const textLayout={'text-field':['get','label'],'text-font':['Local Regular'],'text-size':['interpolate',['linear'],['zoom'],13,12,16,14,18,15],'text-padding':14,'text-pitch-alignment':'viewport','text-rotation-alignment':'viewport','text-max-width':8,'text-variable-anchor':['top','bottom','left','right'],'text-radial-offset':.8};
 add('poi-labels','symbol','pois',textPaint,['all',['!=',['get','label'],''],['!=',['get','category'],'place'],['!=',['get','category'],'transport']],textLayout);
 style.layers.at(-1).minzoom=15.2;
 add('station-labels','symbol','pois',textPaint,['all',['!=',['get','label'],''],eq('category','transport')],textLayout,'rail');
 style.layers.at(-1).minzoom=13.6;
 add('place-labels','symbol','pois',textPaint,['all',['!=',['get','label'],''],['in',['get','category'],['literal',['nature','place']]]],{...textLayout,'text-size':['interpolate',['linear'],['zoom'],11,13,14,16,18,18],'text-letter-spacing':.04});
 add('district-labels','symbol','districtLabels',{'text-color':c.text,'text-halo-color':c.halo,'text-halo-width':2,'text-opacity':['interpolate',['linear'],['zoom'],10,.95,13.5,.5,15.2,0]},null,{'text-field':['get','name'],'text-font':['Local Regular'],'text-size':17,'text-letter-spacing':.12,'text-padding':25},'boundary');
 add('road-labels','symbol','roads',textPaint,['all',eq('category','road'),['!=',['get','label'],''],['in',['get','road_class'],['literal',['major','secondary']]]],{'text-field':['get','label'],'text-font':['Local Regular'],'text-size':13,'symbol-placement':'line','symbol-spacing':300,'text-letter-spacing':.03},'roads');
 style.layers.at(-1).minzoom=14;
 add('landmark-dots','circle','landmarkLabels',{'circle-color':theme==='night'?'#beddeb':'#5c8199','circle-radius':3.5,'circle-stroke-color':c.halo,'circle-stroke-width':1.5},null,{},'pois');style.layers.at(-1).minzoom=13;
 add('landmark-labels','symbol','landmarkLabels',{...textPaint,'text-color':theme==='night'?'#dcebf6':'#345775','text-halo-width':2},null,{...textLayout,'text-field':['get','name'],'text-size':['interpolate',['linear'],['zoom'],13,13,16,16,18,17],'text-padding':22,'symbol-sort-key':-10},'pois');style.layers.at(-1).minzoom=13;
 add('imported-fill','fill','imported',{'fill-color':'#bf8468','fill-opacity':.22});
 add('imported-edge','line','imported',{'line-color':'#ba7057','line-width':2,'line-dasharray':[3,2]});
 add('study-radius','fill','radius',{'fill-color':'#779c96','fill-opacity':.1});
 add('study-radius-edge','line','radius',{'line-color':'#638f83','line-width':1.5,'line-dasharray':[4,3]});
 add('research-fill','fill','research',{'fill-color':['step',['get','score'],'#9aaf94',0,'#a7bc85',40,'#cfad70',60,'#c88671'],'fill-opacity':.28});
 add('research-edge','line','research',{'line-color':theme==='night'?'#d3e6a4':'#536f53','line-width':2,'line-dasharray':[3,2]});
 add('research-labels','symbol','research',{'text-color':theme==='night'?'#e5f3c3':'#385a44','text-halo-color':c.halo,'text-halo-width':2},null, {'text-field':['get','unit_id'],'text-font':['Local Regular'],'text-size':13,'text-allow-overlap':false,'text-padding':16});
 add('study-selected','line','studySelected',{'line-color':'#dc9864','line-width':4});
 add('study-context','circle','context',{'circle-color':['match',['get','category'],'transit','#8d82a9','education','#588c86','health','#c58076','park','#789656','heritage','#bb9862','#a39978'],'circle-radius':4,'circle-stroke-color':c.halo,'circle-stroke-width':1.2});
 add('selected-fill','fill','selected',{'fill-color':'#007aff','fill-opacity':.26},['==',['geometry-type'],'Polygon']);
 add('selected-line','line','selected',{'line-color':theme==='night'?'#7bc6ff':'#007aff','line-width':3},['!=',['geometry-type'],'Point']);
 add('selected-point','circle','selected',{'circle-color':'#007aff','circle-radius':8,'circle-stroke-color':c.halo,'circle-stroke-width':3},['==',['geometry-type'],'Point']);
 add('measure-line','line','measure',{'line-color':'#bc6e53','line-width':3,'line-dasharray':[2,1]},['==',['geometry-type'],'LineString']);
 add('measure-points','circle','measure',{'circle-color':'#fff9df','circle-radius':5,'circle-stroke-color':'#bc6e53','circle-stroke-width':2},['==',['geometry-type'],'Point']);
 return style;
}
