import {insightReportSections} from './assessment-insights.js';
import {VALIDITY,CONSTRAINT_STATUS} from './assessment-evidence.js';
import {zipSync,strToU8} from 'fflate';
import {CREATOR,MODE_NAMES,PROFILES} from './value-domain.js';
import {comparisonPresentation} from './value-workflow.js';
export const xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'');
const display=value=>typeof value==='number'&&Number.isFinite(value)?String(Number(value.toFixed(2))):value??'未提供';
const auxiliarySections=run=>{
 const a=run.auxiliary;if(!a)return [];
 const population=a.population||{},housing=a.housing||{},basis=a.basis==='transaction'?'成交':'挂牌',rate=n=>display(typeof n==='number'?n*100:null)+'%',scopes={'within-unit':'片区内','within-600m':'距片区边界 600m 内','simulated':'模拟情景','none':'无样本'};
 const fields=[['昼间人口情景',population.day,'人',population.detail?.day],['夜间人口代理',population.night,'人',population.detail?.night],['昼间人口密度',population.dayDensity,'人/km²',population.detail?.day],['夜间人口密度',population.nightDensity,'人/km²',population.detail?.night]];
 const rows=[['指标 / 数值','来源 / 时点','口径 / 状态'],...fields.map(([label,value,unit,d])=>[label+' / '+display(value)+' '+unit,(d?.source||population.source||'未接入')+' / '+((d?.dates||[]).join('、')||population.date||'未提供'),d?.simulated?'含模拟假设':'人口模型代理，非信令实测']),...['sale','rent'].map(key=>{const h=housing[key]||{};return [(key==='sale'?'住宅售单价':'住宅租单价')+' / '+display(h.unitPrice)+' '+(h.unit||(key==='sale'?'元/m²':'元/m²/月')),(h.source||'未接入')+' / '+(h.dateRange?.join('—')||h.date||'未提供'),basis+'；'+(h.simulated?'模拟值（非贝壳数据）':display(h.count)+' 条，用户提供待核实')+'；'+(scopes[h.scope]||h.scope||'未注明范围')];})];
 const urls=[...new Set(['day','night'].flatMap(key=>population.detail?.[key]?.urls||[]))];
 const sections=[{title:'人口与住宅市场辅助评估',rows,paragraphs:[
  `基础五维分 ${display(run.baseTotal)}；辅助分 ${display(a.score)}。辅助${a.enabled?'启用':'关闭'}，设置权重 ${rate(a.weight)}，实际权重 ${rate(a.effectiveWeight)}。综合分 = 基础五维分 × (1 − 实际权重) + 辅助分 × 实际权重。`,
  `辅助规则 ${a.version||'未提供'}；统计日期 ${a.asOf||'未提供'}；人口格网版本 ${population.version||'未提供'}。${a.rule?.formula||''}`,
  population.method||'人口模型和空间代理统计。',housing.method||'住宅样本分组统计。',
  ...urls.map(url=>'人口来源原链接：'+url),...(a.limitations||[])
 ]}];
 const samples=['sale','rent'].flatMap(key=>(housing[key]?.samples||[]).map(sample=>({...sample,kind:key})));
 if(samples.length)sections.push({title:'采用的住宅样本',rows:[['样本 / 口径','单价 / 面积','来源 / 日期','原链接'],...samples.slice(0,60).map(sample=>[sample.name+' / '+(sample.kind==='sale'?'售':'租')+' / '+(sample.basis==='transaction'?'成交':'挂牌'),display(sample.unitPrice)+' '+(sample.kind==='sale'?'元/m²':'元/m²/月')+' / '+display(sample.area_m2)+' m² / 距边界 '+display(sample.distanceM)+' m',sample.source+' / '+sample.date,sample.url])],paragraphs:[`本次采用 ${samples.length} 条住宅样本，表格列示前 ${Math.min(60,samples.length)} 条；全部采用样本及其他口径记录均保存在评估完整快照中。导入来源尚待核实。`]});
 return sections;
};
export function reportModel(run,analysis,{note='',reviewer='',reviewNote='',comparison=[],evidence,review=null}={}){
 analysis=run.analysisSnapshot||analysis;
 const status=review?.status==='reviewed'?'项目内已复核':review?.status==='changes'?'需补充资料':'未复核';
 const comparisonView=comparisonPresentation(comparison,comparison);
 return {analysisSnapshot:structuredClone({area:analysis.area,buildingCount:analysis.buildingCount,nearest:analysis.nearest,method:analysis.method}),title:(run.studyContext?.district||'南京市')+'用地更新研究报告',subtitle:run.name+' '+run.unitId,run:structuredClone(run),createdAt:new Date().toISOString(),creator:CREATOR,note,reviewer:review?.actorName||'',reviewNote:review?.note||'',reviewId:review?.id||null,reviewRecord:review,status,comparison:structuredClone(comparison),sections:[
  {title:'研究摘要',paragraphs:[`本报告用于展示 ${run.name} 的空间条件与更新研究画像。数据口径为${MODE_NAMES[run.mode]}，使用${PROFILES[run.profile].name}演示权重。${run.total===null?'当前资料不足，不输出综合关注度。':'演示更新研究关注度为 '+run.total+' / 100。'}结果不代表土地市场价值或实施可行性。`,note||'建议优先核对研究边界、法定规划条件、计容面积、权属及建筑和经营调查。']},
  {title:'研究范围与数据',paragraphs:[`研究轮廓面积约 ${analysis.area} m²，采用 WGS84 / UTM 50N 投影计算；不是登记宗地面积。关联 ${analysis.buildingCount} 个已收录地上建筑主体参考对象（按包围盒中心落入研究范围筛选，非栋数普查）。`,`几何快照 ${run.geometryDate}；设施快照 ${run.spatialDate}。${analysis.method}`,`业务来源：${run.input.source}。业务日期：${run.input.date||'未提供'}。`]},
  {title:'多维评估',rows:[['维度','原始值','分值','权重','证据状态'],...run.dimensions.map(d=>[d.name,d.raw,d.score===null?'缺失':String(d.score),Math.round(d.weight*100)+'%',d.status])],paragraphs:[`有效指标加权覆盖率 ${run.coverage}%。缺失维度：${run.missing.join('、')||'当前演示指标无缺失'}。覆盖率是字段有效性，不是事实可信度。`,...run.dimensions.map(d=>`${d.name}：${d.method}。来源日期 ${d.date||'缺失'}。`)]},
  ...auxiliarySections(run),
  {title:'逐项依据',rows:[['字段 / 原始值 / 单位','来源 / 日期','有效性 / 核实','附件页码'],...(run.fieldEvidence||[]).map(f=>[`${f.label} / ${f.value??'缺失'} ${f.unit}`,`${f.source||'未提供'} / ${f.date||'未提供'}${f.method?'；'+f.method:''}${f.originalEvidence?'；原依据：'+f.originalEvidence.source+'（'+VALIDITY[f.originalEvidence.validity]+'），原值 '+f.originalEvidence.value:''}`,`${f.kind==='simulated'?'模拟假设 / ':''}${VALIDITY[f.validity]} / ${f.verification==='verified'?'已核对':'待核实'}`,f.refs.map(r=>`${r.title} 第 ${r.page} 页`).join('；')||'无附件引用'])],paragraphs:(run.fieldEvidence||[]).flatMap(f=>f.refs.map(r=>`${f.label} — ${r.title} 第 ${r.page} 页：${r.text}（${r.extraction}）`))},
  {title:'独立约束',rows:[['类别','核对状态','事项 / 日期','依据'],...(run.constraints||[]).map(c=>[c.label,CONSTRAINT_STATUS[c.status],`${c.summary||'未补充'} / ${c.date||'未提供'}`,c.refs.map(r=>`${r.title} 第 ${r.page} 页`).join('；')||'无附件引用'])],paragraphs:['规划、权属和安全事项独立列示，不计入五维分数。资料不足不等于没有约束。']},
  {title:'规则适用范围',paragraphs:[run.ruleSnapshot?.scope||'玄武研究流程演示',run.ruleSnapshot?.limitations||'演示规则，未正式发布。']},
  {title:'周边配套',rows:[['类别','最近收录参考点','直线距离'],...Object.entries(analysis.nearest).map(([k,f])=>[({transit:'交通',education:'教育',health:'医疗',park:'公园',daily:'生活服务',heritage:'历史要素'})[k],f?.properties.name||'未收录',f?Math.round(f.distance)+' m':'未知'])],paragraphs:['点位可能是面对象包围盒中心；不代表入口、步行时间、开放时段或服务容量。']},
  ...(comparison.length? [{title:'研究单元比较',rows:[['对象 / 运行记录','数据口径','资料时点','关注度','覆盖率'],...comparison.map((r,i)=>[r.name+' / '+(comparisonView.items[i].runId||'即时原始指标'),MODE_NAMES[r.mode],'边界 '+r.geometryDate+'；设施 '+r.spatialDate+'；业务 '+(r.input.date||'未提供'),comparisonView.items[i].scoreText,r.coverage+'%'])],paragraphs:[comparisonView.reason,'仅在数据模式、评分规则、辅助权重与格网口径一致且指标完整时允许关注度排序；住宅样本日期另列，不构成项目投资排序。',...comparison.filter(r=>r.auxiliary).map(r=>`${r.name}：基础 ${comparisonView.canCompare?display(r.baseTotal):'暂不比较'} 分，辅助 ${comparisonView.canCompare?display(r.auxiliary.score):'暂不比较'} 分，辅助实际权重 ${display(r.auxiliary.effectiveWeight*100)}%，${r.auxiliary.basis==='transaction'?'成交':'挂牌'}；人口 ${r.auxiliary.population?.date||'未提供'}，售价 ${r.auxiliary.housing?.sale?.date||'未提供'}，租价 ${r.auxiliary.housing?.rent?.date||'未提供'}。`)]}]:[]),
  {title:'待核实事项与来源',paragraphs:[...run.limitations,...(evidence?.documents||[]).slice(0,3).map(d=>`${d.title}（${d.date}），${d.publisher}。${d.url}`),'OSM 来源与许可 https://www.openstreetmap.org/copyright']},
  ...insightReportSections(run),
  {title:'版本与复核',paragraphs:[`${run.projectId?'项目编号 '+run.projectId+'；项目数据 V'+run.projectDataVersion+'；保存账户 '+(run.createdByName||run.createdBy)+'。':''}评估运行 ${run.id}；运行时间 ${run.createdAt}；规则 ${run.ruleVersion}；输入标识 ${run.fingerprint}。`,`复核状态：${status}。${review?'账户：'+review.actorName+' / '+review.actorId+'；时间：'+review.reviewedAt+'；意见：'+review.note:'尚无账户复核记录。'} 项目内复核不构成业务审批，规则仍为演示规则。`,CREATOR]}
 ]};
}
export function reportMarkdown(model){return `# ${model.title}\n\n${model.subtitle}\n\n${model.status} · ${MODE_NAMES[model.run.mode]} · 演示规则\n\n`+model.sections.map(s=>'## '+s.title+'\n\n'+(s.rows?'| '+s.rows[0].join(' | ')+' |\n| '+s.rows[0].map(()=> '---').join(' | ')+' |\n'+s.rows.slice(1).map(r=>'| '+r.join(' | ')+' |').join('\n')+'\n\n':'')+s.paragraphs.join('\n\n')).join('\n\n');}
export function reportDocx(model,mapImage){
 const p=(text,style='Normal')=>`<w:p><w:pPr><w:pStyle w:val="${style}"/></w:pPr><w:r><w:t xml:space="preserve">${xml(text)}</w:t></w:r></w:p>`;
 const table=rows=>`<w:tbl><w:tblPr><w:tblW w:w="9638" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:bottom w:val="single" w:sz="4" w:color="DCE3DA"/><w:insideH w:val="single" w:sz="4" w:color="DCE3DA"/></w:tblBorders></w:tblPr><w:tblGrid>${rows[0].map(()=>'<w:gridCol w:w="'+Math.floor(9638/rows[0].length)+'"/>').join('')}</w:tblGrid>${rows.map((r,i)=>`<w:tr><w:trPr><w:cantSplit/>${i===0?'<w:tblHeader/>':''}</w:trPr>${r.map(c=>`<w:tc><w:tcPr><w:tcW w:w="${Math.floor(9638/r.length)}" w:type="dxa"/>${i===0?'<w:shd w:fill="EAF0E2"/>':''}<w:tcMar><w:top w:w="85" w:type="dxa"/><w:left w:w="85" w:type="dxa"/><w:bottom w:w="85" w:type="dxa"/><w:right w:w="85" w:type="dxa"/></w:tcMar></w:tcPr>${p(c,'TableText')}</w:tc>`).join('')}</w:tr>`).join('')}</w:tbl>`;
 const image=mapImage?`<w:p><w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="6096000" cy="3429000"/><wp:docPr id="1" name="研究范围图" descr="所选研究范围、600米观察圈及开放地图背景；非地籍边界"/><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="1" name="研究范围图"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rMap"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="6096000" cy="3429000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`:'';
 const body=p(model.title,'Title')+p(model.subtitle,'Subtitle')+p(`${model.status} · ${MODE_NAMES[model.run.mode]} · 演示规则`)+model.sections.map((s,i)=>p(s.title,'Heading1')+(i===1?image+p('研究范围示意  © OpenStreetMap contributors / ODbL','Caption'):'')+(s.rows?table(s.rows):'')+s.paragraphs.map(t=>p(t)).join('')).join('');
 const files={
  '[Content_Types].xml':`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`,
  '_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rDoc" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
  'word/_rels/document.xml.rels':`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rStyle" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>${mapImage?'<Relationship Id="rMap" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/map.png"/>':''}</Relationships>`,
  'word/document.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1000" w:right="1134" w:bottom="1000" w:left="1134" w:header="400" w:footer="400"/></w:sectPr></w:body></w:document>`,
  'word/styles.xml':`<?xml version="1.0" encoding="UTF-8"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:eastAsia="Noto Sans CJK SC"/><w:sz w:val="22"/><w:lang w:val="zh-CN" w:eastAsia="zh-CN"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="150" w:line="300" w:lineRule="auto"/><w:widowControl/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="100" w:after="240"/></w:pPr><w:rPr><w:b/><w:color w:val="000000"/><w:sz w:val="40"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Subtitle"><w:name w:val="Subtitle"/><w:basedOn w:val="Normal"/><w:rPr><w:sz w:val="26"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:pPr><w:keepNext/><w:outlineLvl w:val="0"/><w:spacing w:before="250" w:after="140"/></w:pPr><w:rPr><w:b/><w:sz w:val="27"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="TableText"><w:name w:val="Table Text"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:after="20" w:line="270" w:lineRule="auto"/></w:pPr><w:rPr><w:sz w:val="20"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Caption"><w:name w:val="caption"/><w:basedOn w:val="Normal"/><w:rPr><w:sz w:val="18"/><w:color w:val="697969"/></w:rPr></w:style></w:styles>`
 };
 const zip=Object.fromEntries(Object.entries(files).map(([k,v])=>[k,strToU8(v)]));if(mapImage)zip['word/media/map.png']=mapImage;return zipSync(zip,{level:6});
}
